#![forbid(unsafe_code)]

//! ANTLR4-based PL/SQL parser backend.
//!
//! This crate contains the vendored PL/SQL grammar from
//! `antlr/grammars-v4` (Apache-2.0) and implements
//! [`plsql_parser::ParseBackend`] using code generated by `antlr4rust`.
//!
//! # Grammar provenance
//!
//! - Source: <https://github.com/antlr/grammars-v4/tree/master/sql/plsql>
//! - `PlSqlLexer.g4` — 2,618 lines
//! - `PlSqlParser.g4` — 10,011 lines
//! - License: Apache-2.0 (see `LICENSE-GRAMMARS.md`)
//!
//! # Codegen
//!
//! Normal builds with `--features antlr-codegen` compile the committed
//! lexer/parser/listener code under `src/generated/`; Java is not required.
//! To refresh the generated code after a grammar or tool change, run the build
//! with `PLSQL_ANTLR_REGEN=1`. CI regenerates into a temporary directory and
//! diffs that output against the committed copy.
//!
//! Without the feature, only the grammar files and this documentation
//! are available.

// Include generated ANTLR code when the feature is enabled.
// The generated modules are PRIVATE — no ANTLR types escape this crate (R20).
#[cfg(feature = "antlr-codegen")]
mod generated {
    #![allow(warnings)]
    #![allow(clippy::all)]

    // Re-export the antlr4rust runtime so generated code can find it.
    extern crate antlr4rust;

    pub mod plsqllexer {
        include!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/src/generated/plsqllexer.rs"
        ));
    }
    pub mod plsqlparser {
        include!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/src/generated/plsqlparser.rs"
        ));
    }
    pub mod plsqlparserlistener {
        include!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/src/generated/plsqlparserlistener.rs"
        ));
    }
    pub mod plsqlparserbaselistener {
        include!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/src/generated/plsqlparserbaselistener.rs"
        ));
    }
}

/// Top-level declaration lowering from source text.
///
/// This module provides a text-scanning pre-parser that recognizes
/// `CREATE [OR REPLACE]` declarations and produces [`plsql_parser::Ast`]
/// nodes.  It will be superseded by proper ANTLR parse-tree lowering
/// once the generated code compiles cleanly.
pub mod lower;

/// Real [`plsql_parser::ParseBackend`] implementation over the ANTLR4 lexer.
///
/// Only compiled when `--features antlr-codegen` is active (the backend
/// depends on the generated lexer code).
#[cfg(feature = "antlr-codegen")]
pub mod backend;

/// Real ANTLR parse-tree → [`plsql_parser::Ast`] lowering.
///
/// Feature-gated on `antlr-codegen`. Supersedes the text-scanning
/// [`lower::lower_source`] for the `ast` field of [`backend::Antlr4RustBackend`].
#[cfg(feature = "antlr-codegen")]
pub mod tree_lower;

#[cfg(feature = "antlr-codegen")]
pub use backend::{ANTLR4RUST_DIAG_CODE, Antlr4RustBackend};

/// Error recovery at statement boundaries (`;` and `/`).
///
/// When the parser encounters unparseable text, recovery skips to the
/// next statement boundary and emits a [`plsql_core::Diagnostic`].
pub mod recover;
