//! Function / procedure wrapper emission (PLSQL-BG-004).
//!
//! Consumes a [`BindingPlan`] and produces the Rust source for the
//! generated wrappers. The output is a single `String` per plan
//! holding one Rust function per `RoutineBinding`; the caller is
//! responsible for placing it into the right file (the CLI bead
//! `PLSQL-BG-012` will own the file layout).
//!
//! This module is intentionally string-templated — no `syn`
//! / `quote!` dependency — because the wrapper shape is tightly
//! constrained (the type system was already pinned in BG-000…BG-003)
//! and the surface this emits is the only Rust we generate. A
//! templated emitter keeps the output deterministic, diff-friendly
//! across releases, and trivially auditable.
//!
//! ## Emission contract
//!
//! For a `procedure foo(p_a IN NUMBER, p_b OUT VARCHAR2)`:
//! ```text
//! pub fn foo(executor: &mut impl OracleExecutor, p_a: i64) -> Result<String, ExecutionError> { … }
//! ```
//!
//! For a `function bar(p_x IN NUMBER) RETURN NUMBER`:
//! ```text
//! pub fn bar(executor: &mut impl OracleExecutor, p_x: i64) -> Result<i64, ExecutionError> { … }
//! ```
//!
//! `Option<T>` is used iff the corresponding `RustTypeRef::nullable`
//! is true. `IN OUT` parameters appear in the function signature
//! AND the return tuple. Multiple `OUT` parameters return a tuple in
//! declaration order; the function's own return type (if any) is the
//! first element.
//!
//! ## /oracle evidence
//!
//! * `DATABASE-REFERENCE.md` — PL/SQL language routing for
//!   parameter-mode semantics (IN / OUT / IN OUT).
//! * `LOW-LEVEL-CATALOGS.md` — supplied-packages bucket for
//!   `DBMS_SQL` / native dynamic SQL boundary (the executor
//!   abstraction in `executor.rs` is what bridges to the driver).

use std::fmt::Write;

use crate::{
    BindingDiagnostic, BindingPlan, ParameterBinding, ParameterMode, RoutineBinding, RoutineKind,
    RustTypeRef,
};

/// Emit Rust source for every routine in `plan`. The output is a
/// single contiguous string; the caller wraps it with whatever
/// `mod` / file-header preamble the target file requires.
#[must_use]
pub fn emit_wrappers(plan: &BindingPlan) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// Generated by plsql-bindgen for {} ({} routines).\n",
        plan.package_name,
        plan.routines.len()
    );
    for routine in &plan.routines {
        emit_routine(&mut out, &plan.package_id, routine);
        out.push('\n');
    }
    for diag in &plan.diagnostics {
        emit_diagnostic_comment(&mut out, diag);
    }
    out
}

/// Map a Rust scalar type path to the `BindValue` constructor that
/// marshals `expr` (an owned value) into a bind. `None` for any type
/// the scalar marshaller does not handle (records, REF cursors,
/// chrono dates, …) — the caller emits a typed error + diagnostic
/// rather than a runtime panic (R13: never silently wrong, never a
/// blanket `unimplemented!()`).
fn scalar_in_marshal(path: &str, expr: &str) -> Option<String> {
    Some(match path {
        "i64" => format!("BindValue::Int({expr})"),
        "i32" | "i16" | "i8" | "u8" | "u16" | "u32" => {
            format!("BindValue::Int(i64::from({expr}))")
        }
        "f64" => format!("BindValue::Float({expr})"),
        "f32" => format!("BindValue::Float(f64::from({expr}))"),
        "String" => format!("BindValue::Text({expr})"),
        "bool" => format!("BindValue::Bool({expr})"),
        "Vec<u8>" => format!("BindValue::Bytes({expr})"),
        _ => return None,
    })
}

/// Inverse of [`scalar_in_marshal`]: a match arm body extracting the
/// Rust value from `bind` (a `&BindValue`). `None` for unsupported.
fn scalar_out_extract(path: &str, bind: &str) -> Option<String> {
    Some(match path {
        "i64" => {
            format!("match {bind} {{ BindValue::Int(v) => *v, _ => return Err(shape_err()) }}")
        }
        "i32" | "i16" | "i8" | "u8" | "u16" | "u32" => format!(
            "match {bind} {{ BindValue::Int(v) => *v as {path}, _ => return Err(shape_err()) }}"
        ),
        "f64" => {
            format!("match {bind} {{ BindValue::Float(v) => *v, _ => return Err(shape_err()) }}")
        }
        "f32" => format!(
            "match {bind} {{ BindValue::Float(v) => *v as f32, _ => return Err(shape_err()) }}"
        ),
        "String" => format!(
            "match {bind} {{ BindValue::Text(v) => v.clone(), _ => return Err(shape_err()) }}"
        ),
        "bool" => {
            format!("match {bind} {{ BindValue::Bool(v) => *v, _ => return Err(shape_err()) }}")
        }
        "Vec<u8>" => format!(
            "match {bind} {{ BindValue::Bytes(v) => v.clone(), _ => return Err(shape_err()) }}"
        ),
        _ => return None,
    })
}

/// Every type the routine needs to marshal (IN/IN OUT params + OUT
/// params + function return). `None` element ⇒ that type is not
/// scalar-marshallable.
fn unsupported_type(r: &RoutineBinding) -> Option<String> {
    for p in &r.parameters {
        if scalar_in_marshal(&p.rust_type.path, "x").is_none() {
            return Some(format!(
                "parameter `{}` type `{}`",
                p.name, p.rust_type.path
            ));
        }
    }
    if let Some(rt) = &r.return_type
        && scalar_out_extract(&rt.path, "b").is_none()
    {
        return Some(format!("return type `{}`", rt.path));
    }
    None
}

fn emit_routine(out: &mut String, package_id: &str, r: &RoutineBinding) {
    if r.autonomous_transaction {
        let _ = writeln!(
            out,
            "/// **PRAGMA AUTONOMOUS_TRANSACTION** — this procedure commits/rolls back its own transaction independently of the caller. The wrapper does not surface a transactional handle; callers must reason about isolation themselves."
        );
    }
    let _ = write!(out, "pub fn {}(executor: &mut impl OracleExecutor", r.name);
    for p in &r.parameters {
        if matches!(p.mode, ParameterMode::In | ParameterMode::InOut) {
            let _ = write!(out, ", {}: {}", p.name, rust_type_in(p));
        }
    }
    let return_type = compute_return_type(r);
    let _ = writeln!(out, ") -> Result<{return_type}, ExecutionError> {{");

    // Types we cannot scalar-marshal get a typed error body — never
    // a runtime `unimplemented!()` panic (the BG-004 audit defect).
    if let Some(why) = unsupported_type(r) {
        let _ = writeln!(
            out,
            "    let _ = executor;\n    \
             // bindgen: {why} has no scalar bind marshalling.\n    \
             Err(ExecutionError {{ code: \"BINDING_UNSUPPORTED_MARSHALLING\".to_string(), \
             message: \"{}: {why} is not scalar-marshallable; supply a manual wrapper or a \
             .plsql-bindgen.toml type override\".to_string() }})",
            r.name
        );
        let _ = writeln!(out, "}}");
        return;
    }

    // Bind layout: slot :1 is the function return (if any), then one
    // slot per parameter in declaration order. This order is the
    // same one `compute_return_type` flattens its tuple in, so the
    // returned output-slot vec maps positionally onto the payload.
    let is_function = matches!(r.kind, RoutineKind::Function);
    let mut binds: Vec<String> = Vec::new();
    let mut call_args: Vec<String> = Vec::new();
    let mut next_slot = 1;
    if is_function {
        binds.push("RoutineArg::Out".to_string());
        next_slot += 1; // :1 reserved for the return assignment
    }
    for p in &r.parameters {
        let slot = next_slot;
        next_slot += 1;
        call_args.push(format!(":{slot}"));
        match p.mode {
            ParameterMode::Out => binds.push("RoutineArg::Out".to_string()),
            ParameterMode::In | ParameterMode::InOut => {
                let ctor = if p.rust_type.nullable {
                    let inner = scalar_in_marshal(&p.rust_type.path, "__v")
                        .expect("checked by unsupported_type");
                    format!(
                        "match {0} {{ Some(__v) => {1}, None => BindValue::Null }}",
                        p.name, inner
                    )
                } else {
                    scalar_in_marshal(&p.rust_type.path, &p.name)
                        .expect("checked by unsupported_type")
                };
                let variant = if matches!(p.mode, ParameterMode::InOut) {
                    "InOut"
                } else {
                    "In"
                };
                binds.push(format!("RoutineArg::{variant}({ctor})"));
            }
        }
    }

    let block = if is_function {
        format!(
            "BEGIN :1 := {package_id}.{}({}); END;",
            r.name,
            call_args.join(", ")
        )
    } else {
        format!(
            "BEGIN {package_id}.{}({}); END;",
            r.name,
            call_args.join(", ")
        )
    };

    let _ = writeln!(out, "    let __args: Vec<RoutineArg> = vec![");
    for b in &binds {
        let _ = writeln!(out, "        {b},");
    }
    let _ = writeln!(out, "    ];");
    let _ = writeln!(
        out,
        "    let __out = executor.call_routine({block:?}, &__args)?;"
    );

    // Output slots, in order: [return?] then each OUT/IN OUT param.
    let mut out_types: Vec<&RustTypeRef> = Vec::new();
    if let Some(rt) = &r.return_type {
        out_types.push(rt);
    }
    for p in &r.parameters {
        if matches!(p.mode, ParameterMode::Out | ParameterMode::InOut) {
            out_types.push(&p.rust_type);
        }
    }

    if out_types.is_empty() {
        let _ = writeln!(out, "    let _ = __out;");
        let _ = writeln!(out, "    Ok(())");
    } else {
        let _ = writeln!(out, "    fn shape_err() -> ExecutionError {{");
        let _ = writeln!(
            out,
            "        ExecutionError {{ code: \"BINDING_RESULT_SHAPE\".to_string(), message: \"executor returned an output bind of an unexpected kind\".to_string() }}"
        );
        let _ = writeln!(out, "    }}");
        let mut exprs: Vec<String> = Vec::new();
        for (i, rt) in out_types.iter().enumerate() {
            let bind = format!("__b{i}");
            let _ = writeln!(
                out,
                "    let {bind} = __out.get({i}).ok_or_else(shape_err)?;"
            );
            let core = scalar_out_extract(&rt.path, &bind).expect("checked by unsupported_type");
            if rt.nullable {
                exprs.push(format!(
                    "if matches!({bind}, BindValue::Null) {{ None }} else {{ Some({core}) }}"
                ));
            } else {
                exprs.push(core);
            }
        }
        if exprs.len() == 1 {
            let _ = writeln!(out, "    Ok({})", exprs.into_iter().next().unwrap());
        } else {
            let _ = writeln!(out, "    Ok(({}))", exprs.join(", "));
        }
    }
    let _ = writeln!(out, "}}");
}

fn rust_type_in(p: &ParameterBinding) -> String {
    if p.rust_type.nullable {
        format!("Option<{}>", p.rust_type.path)
    } else {
        p.rust_type.path.clone()
    }
}

/// Compute the wrapper's `Result` payload type, applying the
/// PL/SQL→Rust translation:
///
/// * Procedure with no OUT / IN OUT params → `()`.
/// * Procedure with one OUT / IN OUT param → `T` (or `Option<T>`).
/// * Procedure with multiple OUT / IN OUT params → `(T1, T2, …)`.
/// * Function with no OUT / IN OUT params → `T` from `return_type`.
/// * Function with OUT / IN OUT params → `(R, T1, T2, …)` where R
///   is the function's `RETURN`.
fn compute_return_type(r: &RoutineBinding) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(rt) = &r.return_type {
        parts.push(rust_type_str(rt));
    }
    for p in &r.parameters {
        if matches!(p.mode, ParameterMode::Out | ParameterMode::InOut) {
            parts.push(rust_type_in(p));
        }
    }
    match parts.len() {
        0 => {
            // Procedure with no OUT params.
            assert!(matches!(r.kind, RoutineKind::Procedure));
            "()".to_string()
        }
        1 => parts.into_iter().next().unwrap(),
        _ => format!("({})", parts.join(", ")),
    }
}

fn rust_type_str(rt: &RustTypeRef) -> String {
    if rt.nullable {
        format!("Option<{}>", rt.path)
    } else {
        rt.path.clone()
    }
}

fn emit_diagnostic_comment(out: &mut String, diag: &BindingDiagnostic) {
    let scope = diag
        .routine
        .as_deref()
        .map(|r| format!("[{r}] "))
        .unwrap_or_default();
    let _ = writeln!(
        out,
        "// bindgen-diag {scope}({}): {}",
        diag.code, diag.message
    );
    if let Some(workaround) = &diag.suggested_workaround {
        let _ = writeln!(out, "//   workaround: {workaround}");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::BindingSeverity;

    fn plan(routines: Vec<RoutineBinding>) -> BindingPlan {
        BindingPlan {
            package_id: "hr.demo_pkg".into(),
            package_name: "demo_pkg".into(),
            routines,
            diagnostics: vec![],
        }
    }

    fn param(name: &str, path: &str, mode: ParameterMode, nullable: bool) -> ParameterBinding {
        ParameterBinding {
            name: name.into(),
            mode,
            rust_type: RustTypeRef {
                path: path.into(),
                nullable,
            },
            has_default: false,
        }
    }

    #[test]
    fn procedure_with_no_out_returns_unit() {
        let r = RoutineBinding {
            name: "do_nothing".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![param("p_a", "i64", ParameterMode::In, false)],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("pub fn do_nothing(executor: &mut impl OracleExecutor, p_a: i64) -> Result<(), ExecutionError>"),
            "{src}"
        );
    }

    #[test]
    fn function_returns_its_return_type() {
        let r = RoutineBinding {
            name: "compute".into(),
            kind: RoutineKind::Function,
            parameters: vec![param("p_x", "i64", ParameterMode::In, false)],
            return_type: Some(RustTypeRef {
                path: "i64".into(),
                nullable: false,
            }),
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(src.contains("-> Result<i64, ExecutionError>"), "{src}");
    }

    #[test]
    fn nullable_in_param_wraps_in_option() {
        let r = RoutineBinding {
            name: "maybe".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![param("p_a", "String", ParameterMode::In, true)],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(src.contains("p_a: Option<String>"), "{src}");
    }

    #[test]
    fn out_param_appears_only_in_return_type() {
        let r = RoutineBinding {
            name: "fetch_name".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![
                param("p_id", "i64", ParameterMode::In, false),
                param("p_name", "String", ParameterMode::Out, false),
            ],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("(executor: &mut impl OracleExecutor, p_id: i64)"),
            "OUT param p_name must NOT appear in the parameter list: {src}"
        );
        assert!(src.contains("-> Result<String, ExecutionError>"), "{src}");
    }

    #[test]
    fn multi_out_params_emit_tuple_return() {
        let r = RoutineBinding {
            name: "split".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![
                param("p_a", "i64", ParameterMode::Out, false),
                param("p_b", "String", ParameterMode::Out, false),
            ],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("-> Result<(i64, String), ExecutionError>"),
            "{src}"
        );
    }

    #[test]
    fn function_with_out_param_emits_tuple_with_return_first() {
        let r = RoutineBinding {
            name: "compute_pair".into(),
            kind: RoutineKind::Function,
            parameters: vec![param("p_extra", "i64", ParameterMode::Out, false)],
            return_type: Some(RustTypeRef {
                path: "i64".into(),
                nullable: false,
            }),
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("-> Result<(i64, i64), ExecutionError>"),
            "{src}"
        );
    }

    #[test]
    fn inout_param_appears_in_both_signature_and_return() {
        let r = RoutineBinding {
            name: "rotate".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![param("p_a", "i64", ParameterMode::InOut, false)],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains(", p_a: i64)"),
            "InOut must appear in args: {src}"
        );
        assert!(src.contains("-> Result<i64, ExecutionError>"), "{src}");
    }

    #[test]
    fn autonomous_transaction_renders_doc_warning() {
        let r = RoutineBinding {
            name: "audit_log".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![],
            return_type: None,
            autonomous_transaction: true,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(src.contains("PRAGMA AUTONOMOUS_TRANSACTION"), "{src}");
    }

    #[test]
    fn diagnostics_appear_as_trailing_comments() {
        let mut p = plan(vec![]);
        p.diagnostics.push(BindingDiagnostic {
            routine: Some("foo".into()),
            code: "BG_REF_CURSOR".into(),
            message: "REF cursor without explicit projection".into(),
            suggested_workaround: Some("Annotate the cursor with --columns".into()),
            span: None,
            severity: BindingSeverity::Skip,
        });
        let src = emit_wrappers(&p);
        assert!(src.contains("bindgen-diag [foo] (BG_REF_CURSOR)"), "{src}");
        assert!(src.contains("workaround: Annotate the cursor"), "{src}");
    }

    #[test]
    fn mixed_in_out_inout_emits_correct_signature_and_tuple_return() {
        // PLSQL-BG-005 acceptance: a procedure with an IN, an OUT,
        // and an IN OUT parameter mixed in declaration order must
        // emit IN + IN OUT in the signature and OUT + IN OUT in the
        // return tuple in declaration order.
        let r = RoutineBinding {
            name: "mix".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![
                param("p_in", "i64", ParameterMode::In, false),
                param("p_out", "String", ParameterMode::Out, false),
                param("p_inout", "f64", ParameterMode::InOut, true),
            ],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        // Signature has p_in + p_inout (IN + IN OUT) only.
        assert!(
            src.contains(
                "pub fn mix(executor: &mut impl OracleExecutor, p_in: i64, p_inout: Option<f64>)"
            ),
            "signature missed IN+IN OUT order or skipped OUT: {src}"
        );
        // Return tuple has OUT + IN OUT in declaration order.
        assert!(
            src.contains("-> Result<(String, Option<f64>), ExecutionError>"),
            "return tuple missed OUT+IN OUT declaration order: {src}"
        );
    }

    #[test]
    fn function_with_mixed_modes_emits_correct_return_tuple() {
        // PLSQL-BG-005 acceptance: a function with one IN + one OUT
        // must emit `Result<(R, OutType), ExecutionError>` with the
        // function return first and OUT second.
        let r = RoutineBinding {
            name: "compute_and_log".into(),
            kind: RoutineKind::Function,
            parameters: vec![
                param("p_in", "i64", ParameterMode::In, false),
                param("p_log", "String", ParameterMode::Out, false),
            ],
            return_type: Some(RustTypeRef {
                path: "i64".into(),
                nullable: false,
            }),
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("-> Result<(i64, String), ExecutionError>"),
            "{src}"
        );
        assert!(
            src.contains("pub fn compute_and_log(executor: &mut impl OracleExecutor, p_in: i64)"),
            "{src}"
        );
    }

    #[test]
    fn emit_is_deterministic_for_identical_input() {
        let r = RoutineBinding {
            name: "x".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![param("p", "i64", ParameterMode::In, false)],
            return_type: None,
            autonomous_transaction: false,
        };
        let a = emit_wrappers(&plan(vec![r.clone()]));
        let b = emit_wrappers(&plan(vec![r]));
        assert_eq!(a, b);
    }

    // --- BG-004 (oracle-hp07): wrapper bodies must be FUNCTIONAL,
    // never `unimplemented!()` ---

    #[test]
    fn no_wrapper_body_is_unimplemented_panic() {
        // The audit defect: every wrapper was `unimplemented!()` and
        // panicked at runtime. No emitted body may contain it now.
        let r = RoutineBinding {
            name: "do_it".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![param("p_a", "i64", ParameterMode::In, false)],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            !src.contains("unimplemented!"),
            "still emits a panic body: {src}"
        );
        assert!(
            src.contains("executor.call_routine("),
            "body must invoke the executor: {src}"
        );
        assert!(
            src.contains("BEGIN hr.demo_pkg.do_it(:1); END;"),
            "must compose the anonymous PL/SQL block: {src}"
        );
    }

    #[test]
    fn scalar_function_marshals_args_and_extracts_return() {
        let r = RoutineBinding {
            name: "add_one".into(),
            kind: RoutineKind::Function,
            parameters: vec![param("p_x", "i64", ParameterMode::In, false)],
            return_type: Some(RustTypeRef {
                path: "i64".into(),
                nullable: false,
            }),
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        // Function return is bind :1, the IN param is :2.
        assert!(
            src.contains("BEGIN :1 := hr.demo_pkg.add_one(:2); END;"),
            "{src}"
        );
        assert!(
            src.contains("RoutineArg::Out,"),
            "return slot must be an Out bind: {src}"
        );
        assert!(
            src.contains("RoutineArg::In(BindValue::Int(p_x))"),
            "IN marshal: {src}"
        );
        assert!(
            src.contains("BindValue::Int(v) => *v"),
            "return extraction: {src}"
        );
    }

    #[test]
    fn nullable_in_param_marshals_null_branch() {
        let r = RoutineBinding {
            name: "maybe".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![param("p_a", "String", ParameterMode::In, true)],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains(
                "match p_a { Some(__v) => BindValue::Text(__v), None => BindValue::Null }"
            ),
            "nullable IN must marshal Some/None: {src}"
        );
    }

    #[test]
    fn out_and_inout_params_become_output_slots() {
        let r = RoutineBinding {
            name: "split".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![
                param("p_in", "i64", ParameterMode::In, false),
                param("p_out", "String", ParameterMode::Out, false),
                param("p_io", "i64", ParameterMode::InOut, false),
            ],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("RoutineArg::In(BindValue::Int(p_in))"),
            "{src}"
        );
        assert!(src.contains("RoutineArg::Out,"), "OUT slot: {src}");
        assert!(
            src.contains("RoutineArg::InOut(BindValue::Int(p_io))"),
            "INOUT slot: {src}"
        );
        // Two output slots → tuple return, extracted positionally.
        assert!(
            src.contains("-> Result<(String, i64), ExecutionError>"),
            "{src}"
        );
        assert!(
            src.contains("__out.get(0)") && src.contains("__out.get(1)"),
            "{src}"
        );
    }

    #[test]
    fn unsupported_type_emits_typed_error_not_panic() {
        // R13: a non-scalar-marshallable type must yield a typed
        // ExecutionError, never `unimplemented!()` / panic.
        let r = RoutineBinding {
            name: "weird".into(),
            kind: RoutineKind::Function,
            parameters: vec![param("p_d", "chrono::NaiveDate", ParameterMode::In, false)],
            return_type: Some(RustTypeRef {
                path: "i64".into(),
                nullable: false,
            }),
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(!src.contains("unimplemented!"), "must not panic: {src}");
        assert!(
            src.contains("BINDING_UNSUPPORTED_MARSHALLING"),
            "must return a typed error for the unmarshallable type: {src}"
        );
        assert!(
            src.contains("chrono::NaiveDate"),
            "error must name the offending type: {src}"
        );
    }
}
