//! Function / procedure wrapper emission.
//!
//! Consumes a [`BindingPlan`] and produces the Rust source for the
//! generated wrappers. The output is a single `String` per plan
//! holding one Rust function per `RoutineBinding`; the caller is
//! responsible for placing it into the right file (the CLI driver
//! owns the file layout).
//!
//! This module is intentionally string-templated — no `syn`
//! / `quote!` dependency — because the wrapper shape is tightly
//! constrained (the type system was already pinned in BG-000…BG-003)
//! and the surface this emits is the only Rust we generate. A
//! templated emitter keeps the output deterministic, diff-friendly
//! across releases, and trivially auditable.
//!
//! ## Emission contract
//!
//! For a `procedure foo(p_a IN NUMBER, p_b OUT VARCHAR2)`:
//! ```text
//! pub fn foo(executor: &mut impl OracleExecutor, p_a: i64) -> Result<String, ExecutionError> { … }
//! ```
//!
//! For a `function bar(p_x IN NUMBER) RETURN NUMBER`:
//! ```text
//! pub fn bar(executor: &mut impl OracleExecutor, p_x: i64) -> Result<i64, ExecutionError> { … }
//! ```
//!
//! `Option<T>` is used iff the corresponding `RustTypeRef::nullable`
//! is true. `IN OUT` parameters appear in the function signature
//! AND the return tuple. Multiple `OUT` parameters return a tuple in
//! declaration order; the function's own return type (if any) is the
//! first element.
//!
//! ## /oracle evidence
//!
//! * `DATABASE-REFERENCE.md` — PL/SQL language routing for
//!   parameter-mode semantics (IN / OUT / IN OUT).
//! * `LOW-LEVEL-CATALOGS.md` — supplied-packages bucket for
//!   `DBMS_SQL` / native dynamic SQL boundary (the executor
//!   abstraction in `executor.rs` is what bridges to the driver).

use std::fmt::Write;

use crate::{
    BindingDiagnostic, BindingPlan, ParameterBinding, ParameterMode, RoutineBinding, RoutineKind,
    RustTypeRef, should_use_defaulted,
};

/// Emit Rust source for every routine in `plan`. The output is a
/// single contiguous string; the caller wraps it with whatever
/// `mod` / file-header preamble the target file requires.
#[must_use]
pub fn emit_wrappers(plan: &BindingPlan) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// Generated by plsql-bindgen for {} ({} routines).\n",
        plan.package_name,
        plan.routines.len()
    );
    for routine in &plan.routines {
        emit_routine(&mut out, &plan.package_id, routine);
        out.push('\n');
    }
    for diag in &plan.diagnostics {
        emit_diagnostic_comment(&mut out, diag);
    }
    out
}

/// Map a Rust scalar type path to the `BindValue` constructor that
/// marshals `expr` (an owned value) into a bind. `None` for any type
/// the scalar marshaller does not handle (records, REF cursors,
/// chrono dates, …) — the caller emits a typed error + diagnostic
/// rather than a runtime panic (R13: never silently wrong, never a
/// blanket `unimplemented!()`).
fn scalar_in_marshal(path: &str, expr: &str) -> Option<String> {
    Some(match path {
        "i64" => format!("BindValue::Int({expr})"),
        "i32" | "i16" | "i8" | "u8" | "u16" | "u32" => {
            format!("BindValue::Int(i64::from({expr}))")
        }
        "f64" => format!("BindValue::Float({expr})"),
        "f32" => format!("BindValue::Float(f64::from({expr}))"),
        "String" => format!("BindValue::Text({expr})"),
        "bool" => format!("BindValue::Bool({expr})"),
        "Vec<u8>" => format!("BindValue::Bytes({expr})"),
        _ => return None,
    })
}

/// Inverse of [`scalar_in_marshal`]: a match arm body extracting the
/// Rust value from `bind` (a `&BindValue`). `None` for unsupported.
fn scalar_out_extract(path: &str, bind: &str) -> Option<String> {
    Some(match path {
        "i64" => {
            format!("match {bind} {{ BindValue::Int(v) => *v, _ => return Err(shape_err()) }}")
        }
        "i32" | "i16" | "i8" | "u8" | "u16" | "u32" => format!(
            "match {bind} {{ BindValue::Int(v) => *v as {path}, _ => return Err(shape_err()) }}"
        ),
        "f64" => {
            format!("match {bind} {{ BindValue::Float(v) => *v, _ => return Err(shape_err()) }}")
        }
        "f32" => format!(
            "match {bind} {{ BindValue::Float(v) => *v as f32, _ => return Err(shape_err()) }}"
        ),
        "String" => format!(
            "match {bind} {{ BindValue::Text(v) => v.clone(), _ => return Err(shape_err()) }}"
        ),
        "bool" => {
            format!("match {bind} {{ BindValue::Bool(v) => *v, _ => return Err(shape_err()) }}")
        }
        "Vec<u8>" => format!(
            "match {bind} {{ BindValue::Bytes(v) => v.clone(), _ => return Err(shape_err()) }}"
        ),
        _ => return None,
    })
}

/// Every type the routine needs to marshal (IN/IN OUT params + OUT
/// params + function return). `None` element ⇒ that type is not
/// scalar-marshallable.
fn unsupported_type(r: &RoutineBinding) -> Option<String> {
    for p in &r.parameters {
        if scalar_in_marshal(&p.rust_type.path, "x").is_none() {
            return Some(format!(
                "parameter `{}` type `{}`",
                p.name, p.rust_type.path
            ));
        }
    }
    if let Some(rt) = &r.return_type
        && scalar_out_extract(&rt.path, "b").is_none()
    {
        return Some(format!("return type `{}`", rt.path));
    }
    None
}

fn emit_routine(out: &mut String, package_id: &str, r: &RoutineBinding) {
    if r.autonomous_transaction {
        let _ = writeln!(
            out,
            "/// **PRAGMA AUTONOMOUS_TRANSACTION** — this procedure commits/rolls back its own transaction independently of the caller. The wrapper does not surface a transactional handle; callers must reason about isolation themselves."
        );
    }
    let _ = write!(out, "pub fn {}(executor: &mut impl OracleExecutor", r.name);
    for p in &r.parameters {
        if matches!(p.mode, ParameterMode::In | ParameterMode::InOut) {
            let _ = write!(out, ", {}: {}", p.name, rust_type_sig(p));
        }
    }
    let return_type = compute_return_type(r);
    let _ = writeln!(out, ") -> Result<{return_type}, ExecutionError> {{");

    // A function carrying neither a RETURN type nor any OUT / IN OUT
    // parameter is degenerate: there is nothing for the wrapper to
    // return, yet a function MUST yield a value. This shape never comes
    // from the parser/catalog path, but the CLI deserializes an
    // untrusted `BindingPlan` via plain serde (main.rs), so a hand-rolled
    // or upstream-buggy plan can present it. Emit a typed-error body
    // (mirroring the unsupported_type path) instead of panicking — the
    // "never panic on bad input" contract requires exit 0 with valid Rust
    // + a typed BINDING_* failure, not a SIGABRT.
    if is_degenerate_function(r) {
        let _ = writeln!(
            out,
            "    let _ = executor;\n    \
             // bindgen: function `{0}` declares no RETURN type and no OUT / IN OUT \
             parameter; there is no value for the wrapper to produce.\n    \
             Err(ExecutionError {{ code: \"BINDING_DEGENERATE_FUNCTION\".to_string(), \
             message: \"{0}: function has no return type and no OUT/IN OUT parameter; the \
             BindingPlan is malformed (a function must return a value)\".to_string() }})",
            r.name
        );
        let _ = writeln!(out, "}}");
        return;
    }

    // Types we cannot scalar-marshal get a typed error body — never
    // a runtime `unimplemented!()` panic (the BG-004 audit defect).
    if let Some(why) = unsupported_type(r) {
        let _ = writeln!(
            out,
            "    let _ = executor;\n    \
             // bindgen: {why} has no scalar bind marshalling.\n    \
             Err(ExecutionError {{ code: \"BINDING_UNSUPPORTED_MARSHALLING\".to_string(), \
             message: \"{}: {why} is not scalar-marshallable; supply a manual wrapper or a \
             .plsql-bindgen.toml type override\".to_string() }})",
            r.name
        );
        let _ = writeln!(out, "}}");
        return;
    }

    // Any IN / IN OUT parameter carrying a `DEFAULT` clause turns the
    // wrapper signature into `Defaulted<T>` and forces a runtime-dynamic
    // bind layout: an `Omit` drops its bind variable entirely (named-
    // argument notation keeps a middle omission legal) so the server
    // evaluates the declared default. Routines with no defaulted params
    // keep the simpler static layout below.
    let is_function = matches!(r.kind, RoutineKind::Function);
    if r.parameters.iter().any(should_use_defaulted) {
        emit_routine_body_dynamic(out, package_id, r, is_function);
        return;
    }

    // Bind layout: slot :1 is the function return (if any), then one
    // slot per parameter in declaration order. This order is the
    // same one `compute_return_type` flattens its tuple in, so the
    // returned output-slot vec maps positionally onto the payload.
    let mut binds: Vec<String> = Vec::new();
    let mut call_args: Vec<String> = Vec::new();
    let mut next_slot = 1;
    if is_function {
        binds.push("RoutineArg::Out".to_string());
        next_slot += 1; // :1 reserved for the return assignment
    }
    for p in &r.parameters {
        let slot = next_slot;
        next_slot += 1;
        call_args.push(format!(":{slot}"));
        match p.mode {
            ParameterMode::Out => binds.push("RoutineArg::Out".to_string()),
            ParameterMode::In | ParameterMode::InOut => {
                let ctor = if p.rust_type.nullable {
                    let inner = scalar_in_marshal(&p.rust_type.path, "__v")
                        .expect("checked by unsupported_type");
                    format!(
                        "match {0} {{ Some(__v) => {1}, None => BindValue::Null }}",
                        p.name, inner
                    )
                } else {
                    scalar_in_marshal(&p.rust_type.path, &p.name)
                        .expect("checked by unsupported_type")
                };
                let variant = if matches!(p.mode, ParameterMode::InOut) {
                    "InOut"
                } else {
                    "In"
                };
                binds.push(format!("RoutineArg::{variant}({ctor})"));
            }
        }
    }

    let block = if is_function {
        format!(
            "BEGIN :1 := {package_id}.{}({}); END;",
            r.name,
            call_args.join(", ")
        )
    } else {
        format!(
            "BEGIN {package_id}.{}({}); END;",
            r.name,
            call_args.join(", ")
        )
    };

    let _ = writeln!(out, "    let __args: Vec<RoutineArg> = vec![");
    for b in &binds {
        let _ = writeln!(out, "        {b},");
    }
    let _ = writeln!(out, "    ];");
    let _ = writeln!(
        out,
        "    let __out = executor.call_routine({block:?}, &__args)?;"
    );

    // Output slots, in order: [return?] then each OUT/IN OUT param.
    let mut out_types: Vec<&RustTypeRef> = Vec::new();
    if let Some(rt) = &r.return_type {
        out_types.push(rt);
    }
    for p in &r.parameters {
        if matches!(p.mode, ParameterMode::Out | ParameterMode::InOut) {
            out_types.push(&p.rust_type);
        }
    }

    if out_types.is_empty() {
        let _ = writeln!(out, "    let _ = __out;");
        let _ = writeln!(out, "    Ok(())");
    } else {
        let _ = writeln!(out, "    fn shape_err() -> ExecutionError {{");
        let _ = writeln!(
            out,
            "        ExecutionError {{ code: \"BINDING_RESULT_SHAPE\".to_string(), message: \"executor returned an output bind of an unexpected kind\".to_string() }}"
        );
        let _ = writeln!(out, "    }}");
        let mut exprs: Vec<String> = Vec::new();
        for (i, rt) in out_types.iter().enumerate() {
            let bind = format!("__b{i}");
            let _ = writeln!(
                out,
                "    let {bind} = __out.get({i}).ok_or_else(shape_err)?;"
            );
            let core = scalar_out_extract(&rt.path, &bind).expect("checked by unsupported_type");
            if rt.nullable {
                exprs.push(format!(
                    "if matches!({bind}, BindValue::Null) {{ None }} else {{ Some({core}) }}"
                ));
            } else {
                exprs.push(core);
            }
        }
        if exprs.len() == 1 {
            let _ = writeln!(out, "    Ok({})", exprs.into_iter().next().unwrap());
        } else {
            let _ = writeln!(out, "    Ok(({}))", exprs.join(", "));
        }
    }
    let _ = writeln!(out, "}}");
}

/// The Rust type used for an IN / IN OUT parameter in the wrapper's
/// *signature*. For a defaulted parameter this is `Defaulted<T>` (or
/// `Defaulted<Option<T>>` when also nullable), mirroring
/// [`crate::with_defaulted`]; otherwise it is the plain value type.
fn rust_type_sig(p: &ParameterBinding) -> String {
    let value = rust_type_in(p);
    if should_use_defaulted(p) {
        format!("Defaulted<{value}>")
    } else {
        value
    }
}

/// The Rust type a parameter *carries by value* (`T` or `Option<T>`).
/// Used for the return tuple, where even an IN OUT defaulted parameter
/// surfaces its read-back value as `T`/`Option<T>`, never `Defaulted<T>`
/// (the `Defaulted` wrapper only models the inbound omit/null/value
/// choice, which has no meaning on the way back out).
fn rust_type_in(p: &ParameterBinding) -> String {
    if p.rust_type.nullable {
        format!("Option<{}>", p.rust_type.path)
    } else {
        p.rust_type.path.clone()
    }
}

/// Emit the body of a routine that has at least one defaulted IN / IN OUT
/// parameter. The bind layout is built at runtime so that a
/// `Defaulted::Omit` argument contributes no bind variable and the server
/// evaluates the declared default. The anonymous block uses named-argument
/// notation (`p_name => :n`) for every parameter so omitting a middle
/// default-bearing argument remains legal PL/SQL; slot numbers are assigned
/// dynamically as binds are pushed.
fn emit_routine_body_dynamic(
    out: &mut String,
    package_id: &str,
    r: &RoutineBinding,
    is_function: bool,
) {
    // shape_err is needed whenever there is any output slot (a function
    // return or any OUT / IN OUT parameter). Emit it up front when used.
    let has_output = r.return_type.is_some()
        || r.parameters
            .iter()
            .any(|p| matches!(p.mode, ParameterMode::Out | ParameterMode::InOut));
    if has_output {
        let _ = writeln!(out, "    fn shape_err() -> ExecutionError {{");
        let _ = writeln!(
            out,
            "        ExecutionError {{ code: \"BINDING_RESULT_SHAPE\".to_string(), message: \"executor returned an output bind of an unexpected kind\".to_string() }}"
        );
        let _ = writeln!(out, "    }}");
    }

    let _ = writeln!(out, "    let mut __args: Vec<RoutineArg> = Vec::new();");
    let _ = writeln!(out, "    let mut __call: Vec<String> = Vec::new();");
    // :1 is reserved for the function return assignment; parameter slots
    // start at :2 for functions and :1 for procedures. The counter holds
    // the NEXT slot number to hand out.
    let first_param_slot = if is_function { 2 } else { 1 };
    let _ = writeln!(out, "    let mut __slot: u32 = {first_param_slot};");
    if is_function {
        // The return slot is always bound and always first in the output
        // sequence; it never participates in named-argument notation.
        let _ = writeln!(out, "    __args.push(RoutineArg::Out);");
    }

    for p in &r.parameters {
        emit_dynamic_param_bind(out, p);
    }

    let prefix = if is_function { ":1 := " } else { "" };
    let _ = writeln!(
        out,
        "    let __block = format!(\"BEGIN {prefix}{package_id}.{}({{}}); END;\", __call.join(\", \"));",
        r.name
    );
    let _ = writeln!(
        out,
        "    let __out = executor.call_routine(&__block, &__args)?;"
    );

    // Output extraction. Output slots arrive in the order they were pushed
    // into __args: the function return first (if any), then each OUT slot
    // and each non-omitted IN OUT slot in declaration order. Because an
    // omitted IN OUT contributes no output, we cannot statically index the
    // return vec; we walk it positionally at runtime via a cursor.
    let mut out_types: Vec<(&RustTypeRef, Option<&ParameterBinding>)> = Vec::new();
    if let Some(rt) = &r.return_type {
        out_types.push((rt, None));
    }
    for p in &r.parameters {
        if matches!(p.mode, ParameterMode::Out | ParameterMode::InOut) {
            out_types.push((&p.rust_type, Some(p)));
        }
    }

    if out_types.is_empty() {
        let _ = writeln!(out, "    let _ = __out;");
        let _ = writeln!(out, "    Ok(())");
    } else {
        let _ = writeln!(out, "    let mut __cursor = 0usize;");
        let mut exprs: Vec<String> = Vec::new();
        for (idx, (rt, owner)) in out_types.iter().enumerate() {
            let bind = format!("__b{idx}");
            // An omitted IN OUT defaulted parameter has no output slot to
            // read back: omitting an IN OUT means there is no actual
            // argument for the server to write into. Surface that as a
            // typed error rather than mis-aligning the output cursor.
            let omittable_inout = owner.is_some_and(|p| {
                matches!(p.mode, ParameterMode::InOut) && should_use_defaulted(p)
            });
            let core = scalar_out_extract(&rt.path, &bind).expect("checked by unsupported_type");
            let value_expr = if rt.nullable {
                format!("if matches!({bind}, BindValue::Null) {{ None }} else {{ Some({core}) }}")
            } else {
                core
            };
            if omittable_inout {
                let pname = owner.expect("omittable_inout implies owner").name.as_str();
                let _ = writeln!(
                    out,
                    "    let __r{idx} = if matches!({pname}, Defaulted::Omit) {{"
                );
                let _ = writeln!(
                    out,
                    "        return Err(ExecutionError {{ code: \"BINDING_OMIT_INOUT\".to_string(), message: \"IN OUT parameter `{pname}` was omitted; an omitted IN OUT has no output to read back\".to_string() }});"
                );
                let _ = writeln!(out, "    }} else {{");
                let _ = writeln!(
                    out,
                    "        let {bind} = __out.get(__cursor).ok_or_else(shape_err)?;"
                );
                let _ = writeln!(out, "        __cursor += 1;");
                let _ = writeln!(out, "        {value_expr}");
                let _ = writeln!(out, "    }};");
                exprs.push(format!("__r{idx}"));
            } else {
                let _ = writeln!(
                    out,
                    "    let {bind} = __out.get(__cursor).ok_or_else(shape_err)?;"
                );
                let _ = writeln!(out, "    __cursor += 1;");
                exprs.push(value_expr);
            }
        }
        if exprs.len() == 1 {
            let _ = writeln!(out, "    Ok({})", exprs.into_iter().next().unwrap());
        } else {
            let _ = writeln!(out, "    Ok(({}))", exprs.join(", "));
        }
    }
    let _ = writeln!(out, "}}");
}

/// Emit the runtime bind-push for a single parameter inside the dynamic
/// body. OUT params always bind an `Out` slot with a fixed `:n`. IN / IN OUT
/// params bind a value; defaulted ones branch on the three `Defaulted`
/// states, with `Omit` skipping the bind entirely (named notation keeps the
/// remaining slots legal).
fn emit_dynamic_param_bind(out: &mut String, p: &ParameterBinding) {
    let name = &p.name;
    match p.mode {
        ParameterMode::Out => {
            let _ = writeln!(out, "    {{");
            let _ = writeln!(out, "        let __n = __slot; __slot += 1;");
            let _ = writeln!(out, "        __call.push(format!(\"{name} => :{{__n}}\"));");
            let _ = writeln!(out, "        __args.push(RoutineArg::Out);");
            let _ = writeln!(out, "    }}");
        }
        ParameterMode::In | ParameterMode::InOut => {
            let variant = if matches!(p.mode, ParameterMode::InOut) {
                "InOut"
            } else {
                "In"
            };
            if should_use_defaulted(p) {
                // value_ctor marshals the inner value bound to `__v`
                // (`Option<T>` when nullable, plain `T` otherwise).
                let value_ctor = dynamic_value_ctor(p, "__v");
                let _ = writeln!(out, "    match &{name} {{");
                // Omit: contribute no bind variable; the named-argument
                // notation already omits this position from the call.
                let _ = writeln!(out, "        Defaulted::Omit => {{}}");
                let _ = writeln!(out, "        Defaulted::Null => {{");
                let _ = writeln!(out, "            let __n = __slot; __slot += 1;");
                let _ = writeln!(out, "            __call.push(format!(\"{name} => :{{__n}}\"));");
                let _ = writeln!(
                    out,
                    "            __args.push(RoutineArg::{variant}(BindValue::Null));"
                );
                let _ = writeln!(out, "        }}");
                let _ = writeln!(out, "        Defaulted::Value(__v) => {{");
                let _ = writeln!(out, "            let __n = __slot; __slot += 1;");
                let _ = writeln!(out, "            __call.push(format!(\"{name} => :{{__n}}\"));");
                let _ = writeln!(
                    out,
                    "            __args.push(RoutineArg::{variant}({value_ctor}));"
                );
                let _ = writeln!(out, "        }}");
                let _ = writeln!(out, "    }}");
            } else {
                let by_ref = format!("&{name}");
                let ctor = dynamic_value_ctor(p, &by_ref);
                let _ = writeln!(out, "    {{");
                let _ = writeln!(out, "        let __n = __slot; __slot += 1;");
                let _ = writeln!(out, "        __call.push(format!(\"{name} => :{{__n}}\"));");
                let _ = writeln!(out, "        __args.push(RoutineArg::{variant}({ctor}));");
                let _ = writeln!(out, "    }}");
            }
        }
    }
}

/// Build the `BindValue` constructor expression for an IN / IN OUT value
/// held in `src`. When the parameter is nullable, `src` is an `Option<T>`
/// (or `&Option<T>` reference) and we match Some/None; otherwise `src` is
/// the value directly. The inner scalar is taken by value via `.clone()`
/// of the matched binding so the dynamic match arms can borrow `&name`.
fn dynamic_value_ctor(p: &ParameterBinding, src: &str) -> String {
    let path = &p.rust_type.path;
    if p.rust_type.nullable {
        let inner = scalar_in_marshal(path, "__iv").expect("checked by unsupported_type");
        format!("match {src} {{ Some(__iv) => {{ let __iv = (*__iv).clone(); {inner} }}, None => BindValue::Null }}")
    } else {
        // `src` is always a reference expression (`&name` or a `&T` match
        // binding); parenthesise before `.clone()` so the cloned value is
        // owned `T`, not `&T`.
        let cloned = format!("({src}).clone()");
        scalar_in_marshal(path, &cloned).expect("checked by unsupported_type")
    }
}

/// Compute the wrapper's `Result` payload type, applying the
/// PL/SQL→Rust translation:
///
/// * Procedure with no OUT / IN OUT params → `()`.
/// * Procedure with one OUT / IN OUT param → `T` (or `Option<T>`).
/// * Procedure with multiple OUT / IN OUT params → `(T1, T2, …)`.
/// * Function with no OUT / IN OUT params → `T` from `return_type`.
/// * Function with OUT / IN OUT params → `(R, T1, T2, …)` where R
///   is the function's `RETURN`.
fn compute_return_type(r: &RoutineBinding) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(rt) = &r.return_type {
        parts.push(rust_type_str(rt));
    }
    for p in &r.parameters {
        if matches!(p.mode, ParameterMode::Out | ParameterMode::InOut) {
            parts.push(rust_type_in(p));
        }
    }
    match parts.len() {
        // No RETURN and no OUT / IN OUT param. For a procedure this is the
        // unit return. For a (degenerate, malformed-plan) function this is
        // never reached down the happy path — `emit_routine` diverts such a
        // routine to a typed-error body via `is_degenerate_function` before
        // the value is consumed — but we still return `()` rather than
        // asserting so this helper never panics on untrusted input (the CLI
        // deserializes an unvalidated `BindingPlan`). Asserting on
        // attacker-shaped input was the BINDING_DEGENERATE_FUNCTION defect.
        0 => "()".to_string(),
        1 => parts.into_iter().next().unwrap(),
        _ => format!("({})", parts.join(", ")),
    }
}

/// A function with neither a RETURN type nor any OUT / IN OUT parameter is
/// degenerate: a function must produce a value, yet this shape yields none.
/// The parser / catalog path can never construct it, but the CLI accepts an
/// untrusted `BindingPlan` over serde, so the emitter must fail closed with a
/// typed diagnostic rather than panic.
fn is_degenerate_function(r: &RoutineBinding) -> bool {
    matches!(r.kind, RoutineKind::Function)
        && r.return_type.is_none()
        && !r
            .parameters
            .iter()
            .any(|p| matches!(p.mode, ParameterMode::Out | ParameterMode::InOut))
}

fn rust_type_str(rt: &RustTypeRef) -> String {
    if rt.nullable {
        format!("Option<{}>", rt.path)
    } else {
        rt.path.clone()
    }
}

fn emit_diagnostic_comment(out: &mut String, diag: &BindingDiagnostic) {
    let scope = diag
        .routine
        .as_deref()
        .map(|r| format!("[{r}] "))
        .unwrap_or_default();
    let _ = writeln!(
        out,
        "// bindgen-diag {scope}({}): {}",
        diag.code, diag.message
    );
    if let Some(workaround) = &diag.suggested_workaround {
        let _ = writeln!(out, "//   workaround: {workaround}");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::BindingSeverity;

    fn plan(routines: Vec<RoutineBinding>) -> BindingPlan {
        BindingPlan {
            package_id: "hr.demo_pkg".into(),
            package_name: "demo_pkg".into(),
            routines,
            diagnostics: vec![],
        }
    }

    fn param(name: &str, path: &str, mode: ParameterMode, nullable: bool) -> ParameterBinding {
        ParameterBinding {
            name: name.into(),
            mode,
            rust_type: RustTypeRef {
                path: path.into(),
                nullable,
            },
            has_default: false,
        }
    }

    fn defaulted_param(
        name: &str,
        path: &str,
        mode: ParameterMode,
        nullable: bool,
    ) -> ParameterBinding {
        let mut p = param(name, path, mode, nullable);
        p.has_default = true;
        p
    }

    #[test]
    fn procedure_with_no_out_returns_unit() {
        let r = RoutineBinding {
            name: "do_nothing".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![param("p_a", "i64", ParameterMode::In, false)],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("pub fn do_nothing(executor: &mut impl OracleExecutor, p_a: i64) -> Result<(), ExecutionError>"),
            "{src}"
        );
    }

    #[test]
    fn function_returns_its_return_type() {
        let r = RoutineBinding {
            name: "compute".into(),
            kind: RoutineKind::Function,
            parameters: vec![param("p_x", "i64", ParameterMode::In, false)],
            return_type: Some(RustTypeRef {
                path: "i64".into(),
                nullable: false,
            }),
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(src.contains("-> Result<i64, ExecutionError>"), "{src}");
    }

    #[test]
    fn nullable_in_param_wraps_in_option() {
        let r = RoutineBinding {
            name: "maybe".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![param("p_a", "String", ParameterMode::In, true)],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(src.contains("p_a: Option<String>"), "{src}");
    }

    #[test]
    fn out_param_appears_only_in_return_type() {
        let r = RoutineBinding {
            name: "fetch_name".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![
                param("p_id", "i64", ParameterMode::In, false),
                param("p_name", "String", ParameterMode::Out, false),
            ],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("(executor: &mut impl OracleExecutor, p_id: i64)"),
            "OUT param p_name must NOT appear in the parameter list: {src}"
        );
        assert!(src.contains("-> Result<String, ExecutionError>"), "{src}");
    }

    #[test]
    fn multi_out_params_emit_tuple_return() {
        let r = RoutineBinding {
            name: "split".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![
                param("p_a", "i64", ParameterMode::Out, false),
                param("p_b", "String", ParameterMode::Out, false),
            ],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("-> Result<(i64, String), ExecutionError>"),
            "{src}"
        );
    }

    #[test]
    fn function_with_out_param_emits_tuple_with_return_first() {
        let r = RoutineBinding {
            name: "compute_pair".into(),
            kind: RoutineKind::Function,
            parameters: vec![param("p_extra", "i64", ParameterMode::Out, false)],
            return_type: Some(RustTypeRef {
                path: "i64".into(),
                nullable: false,
            }),
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("-> Result<(i64, i64), ExecutionError>"),
            "{src}"
        );
    }

    #[test]
    fn inout_param_appears_in_both_signature_and_return() {
        let r = RoutineBinding {
            name: "rotate".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![param("p_a", "i64", ParameterMode::InOut, false)],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains(", p_a: i64)"),
            "InOut must appear in args: {src}"
        );
        assert!(src.contains("-> Result<i64, ExecutionError>"), "{src}");
    }

    #[test]
    fn autonomous_transaction_renders_doc_warning() {
        let r = RoutineBinding {
            name: "audit_log".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![],
            return_type: None,
            autonomous_transaction: true,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(src.contains("PRAGMA AUTONOMOUS_TRANSACTION"), "{src}");
    }

    #[test]
    fn diagnostics_appear_as_trailing_comments() {
        let mut p = plan(vec![]);
        p.diagnostics.push(BindingDiagnostic {
            routine: Some("foo".into()),
            code: "BG_REF_CURSOR".into(),
            message: "REF cursor without explicit projection".into(),
            suggested_workaround: Some("Annotate the cursor with --columns".into()),
            span: None,
            severity: BindingSeverity::Skip,
        });
        let src = emit_wrappers(&p);
        assert!(src.contains("bindgen-diag [foo] (BG_REF_CURSOR)"), "{src}");
        assert!(src.contains("workaround: Annotate the cursor"), "{src}");
    }

    #[test]
    fn mixed_in_out_inout_emits_correct_signature_and_tuple_return() {
        // PLSQL-BG-005 acceptance: a procedure with an IN, an OUT,
        // and an IN OUT parameter mixed in declaration order must
        // emit IN + IN OUT in the signature and OUT + IN OUT in the
        // return tuple in declaration order.
        let r = RoutineBinding {
            name: "mix".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![
                param("p_in", "i64", ParameterMode::In, false),
                param("p_out", "String", ParameterMode::Out, false),
                param("p_inout", "f64", ParameterMode::InOut, true),
            ],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        // Signature has p_in + p_inout (IN + IN OUT) only.
        assert!(
            src.contains(
                "pub fn mix(executor: &mut impl OracleExecutor, p_in: i64, p_inout: Option<f64>)"
            ),
            "signature missed IN+IN OUT order or skipped OUT: {src}"
        );
        // Return tuple has OUT + IN OUT in declaration order.
        assert!(
            src.contains("-> Result<(String, Option<f64>), ExecutionError>"),
            "return tuple missed OUT+IN OUT declaration order: {src}"
        );
    }

    #[test]
    fn function_with_mixed_modes_emits_correct_return_tuple() {
        // PLSQL-BG-005 acceptance: a function with one IN + one OUT
        // must emit `Result<(R, OutType), ExecutionError>` with the
        // function return first and OUT second.
        let r = RoutineBinding {
            name: "compute_and_log".into(),
            kind: RoutineKind::Function,
            parameters: vec![
                param("p_in", "i64", ParameterMode::In, false),
                param("p_log", "String", ParameterMode::Out, false),
            ],
            return_type: Some(RustTypeRef {
                path: "i64".into(),
                nullable: false,
            }),
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("-> Result<(i64, String), ExecutionError>"),
            "{src}"
        );
        assert!(
            src.contains("pub fn compute_and_log(executor: &mut impl OracleExecutor, p_in: i64)"),
            "{src}"
        );
    }

    #[test]
    fn emit_is_deterministic_for_identical_input() {
        let r = RoutineBinding {
            name: "x".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![param("p", "i64", ParameterMode::In, false)],
            return_type: None,
            autonomous_transaction: false,
        };
        let a = emit_wrappers(&plan(vec![r.clone()]));
        let b = emit_wrappers(&plan(vec![r]));
        assert_eq!(a, b);
    }

    // --- BG-004 (oracle-hp07): wrapper bodies must be FUNCTIONAL,
    // never `unimplemented!()` ---

    #[test]
    fn no_wrapper_body_is_unimplemented_panic() {
        // The audit defect: every wrapper was `unimplemented!()` and
        // panicked at runtime. No emitted body may contain it now.
        let r = RoutineBinding {
            name: "do_it".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![param("p_a", "i64", ParameterMode::In, false)],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            !src.contains("unimplemented!"),
            "still emits a panic body: {src}"
        );
        assert!(
            src.contains("executor.call_routine("),
            "body must invoke the executor: {src}"
        );
        assert!(
            src.contains("BEGIN hr.demo_pkg.do_it(:1); END;"),
            "must compose the anonymous PL/SQL block: {src}"
        );
    }

    #[test]
    fn scalar_function_marshals_args_and_extracts_return() {
        let r = RoutineBinding {
            name: "add_one".into(),
            kind: RoutineKind::Function,
            parameters: vec![param("p_x", "i64", ParameterMode::In, false)],
            return_type: Some(RustTypeRef {
                path: "i64".into(),
                nullable: false,
            }),
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        // Function return is bind :1, the IN param is :2.
        assert!(
            src.contains("BEGIN :1 := hr.demo_pkg.add_one(:2); END;"),
            "{src}"
        );
        assert!(
            src.contains("RoutineArg::Out,"),
            "return slot must be an Out bind: {src}"
        );
        assert!(
            src.contains("RoutineArg::In(BindValue::Int(p_x))"),
            "IN marshal: {src}"
        );
        assert!(
            src.contains("BindValue::Int(v) => *v"),
            "return extraction: {src}"
        );
    }

    #[test]
    fn nullable_in_param_marshals_null_branch() {
        let r = RoutineBinding {
            name: "maybe".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![param("p_a", "String", ParameterMode::In, true)],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains(
                "match p_a { Some(__v) => BindValue::Text(__v), None => BindValue::Null }"
            ),
            "nullable IN must marshal Some/None: {src}"
        );
    }

    #[test]
    fn out_and_inout_params_become_output_slots() {
        let r = RoutineBinding {
            name: "split".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![
                param("p_in", "i64", ParameterMode::In, false),
                param("p_out", "String", ParameterMode::Out, false),
                param("p_io", "i64", ParameterMode::InOut, false),
            ],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("RoutineArg::In(BindValue::Int(p_in))"),
            "{src}"
        );
        assert!(src.contains("RoutineArg::Out,"), "OUT slot: {src}");
        assert!(
            src.contains("RoutineArg::InOut(BindValue::Int(p_io))"),
            "INOUT slot: {src}"
        );
        // Two output slots → tuple return, extracted positionally.
        assert!(
            src.contains("-> Result<(String, i64), ExecutionError>"),
            "{src}"
        );
        assert!(
            src.contains("__out.get(0)") && src.contains("__out.get(1)"),
            "{src}"
        );
    }

    #[test]
    fn unsupported_type_emits_typed_error_not_panic() {
        // R13: a non-scalar-marshallable type must yield a typed
        // ExecutionError, never `unimplemented!()` / panic.
        let r = RoutineBinding {
            name: "weird".into(),
            kind: RoutineKind::Function,
            parameters: vec![param("p_d", "chrono::NaiveDate", ParameterMode::In, false)],
            return_type: Some(RustTypeRef {
                path: "i64".into(),
                nullable: false,
            }),
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(!src.contains("unimplemented!"), "must not panic: {src}");
        assert!(
            src.contains("BINDING_UNSUPPORTED_MARSHALLING"),
            "must return a typed error for the unmarshallable type: {src}"
        );
        assert!(
            src.contains("chrono::NaiveDate"),
            "error must name the offending type: {src}"
        );
    }

    // --- oracle-ajm2.8: a degenerate function (no RETURN type, no OUT /
    // IN OUT parameter) is a malformed BindingPlan the untrusted-input CLI
    // can deserialize. The emitter must fail closed with a typed error body,
    // never an `assert!` panic / SIGABRT. ---

    #[test]
    fn degenerate_function_emits_typed_error_not_panic() {
        // Before the fix this routine drove compute_return_type into
        // `assert!(matches!(r.kind, Procedure))` and aborted. It must now
        // produce valid Rust with a typed BINDING_DEGENERATE_FUNCTION body.
        let r = RoutineBinding {
            name: "f".into(),
            kind: RoutineKind::Function,
            parameters: vec![],
            return_type: None,
            autonomous_transaction: false,
        };
        // emit_wrappers must not panic on this untrusted shape.
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("BINDING_DEGENERATE_FUNCTION"),
            "degenerate function must emit a typed error body: {src}"
        );
        assert!(!src.contains("unimplemented!"), "must not panic-body: {src}");
        // The signature still type-checks: a function with no return is
        // forced to `Result<(), _>` so the emitted error body is valid Rust.
        assert!(
            src.contains("pub fn f(executor: &mut impl OracleExecutor) -> Result<(), ExecutionError>"),
            "degenerate function signature must be well-formed: {src}"
        );
        // No executor call is composed — there is nothing to invoke.
        assert!(
            !src.contains("executor.call_routine("),
            "degenerate function must not compose a server call: {src}"
        );
    }

    #[test]
    fn compute_return_type_does_not_panic_on_degenerate_function() {
        // Direct unit guard on the helper that previously asserted: a
        // Function with no return / no OUT param must yield `()` (and not
        // abort), so any caller is panic-safe on untrusted input.
        let r = RoutineBinding {
            name: "f".into(),
            kind: RoutineKind::Function,
            parameters: vec![],
            return_type: None,
            autonomous_transaction: false,
        };
        assert_eq!(compute_return_type(&r), "()");
        assert!(is_degenerate_function(&r));
        // A normal function is not flagged degenerate.
        let ok = RoutineBinding {
            name: "g".into(),
            kind: RoutineKind::Function,
            parameters: vec![],
            return_type: Some(RustTypeRef {
                path: "i64".into(),
                nullable: false,
            }),
            autonomous_transaction: false,
        };
        assert!(!is_degenerate_function(&ok));
        // A plain procedure with no OUT is the legitimate unit case.
        let proc = RoutineBinding {
            name: "p".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![],
            return_type: None,
            autonomous_transaction: false,
        };
        assert!(!is_degenerate_function(&proc));
        assert_eq!(compute_return_type(&proc), "()");
    }

    // --- oracle-qm3q.13: defaulted IN / IN OUT params must surface as
    // `Defaulted<T>` in the signature and bind via an omittable, named-
    // argument layout so Oracle's declared-default path is reachable. ---

    #[test]
    fn defaulted_in_param_uses_defaulted_type_in_signature() {
        // The defect: `proc(p_a IN NUMBER DEFAULT 5)` emitted a required
        // `p_a: i64` and always bound :1, so the omit/declared-default
        // path was inexpressible. It must now be `Defaulted<i64>`.
        let r = RoutineBinding {
            name: "proc_with_default".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![defaulted_param("p_a", "i64", ParameterMode::In, false)],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("p_a: Defaulted<i64>"),
            "defaulted IN param must surface as Defaulted<T>: {src}"
        );
        // Not the old required-binding shape.
        assert!(
            !src.contains(", p_a: i64)"),
            "must NOT emit the plain required type: {src}"
        );
    }

    #[test]
    fn defaulted_param_omit_drops_bind_and_uses_named_notation() {
        let r = RoutineBinding {
            name: "proc_with_default".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![defaulted_param("p_a", "i64", ParameterMode::In, false)],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        // Omit contributes no bind.
        assert!(
            src.contains("Defaulted::Omit => {}"),
            "Omit must push no bind: {src}"
        );
        // Null binds an explicit NULL (distinct from Omit).
        assert!(
            src.contains("Defaulted::Null =>") && src.contains("RoutineArg::In(BindValue::Null)"),
            "Null must bind BindValue::Null: {src}"
        );
        // Value marshals the scalar.
        assert!(
            src.contains("Defaulted::Value(__v) =>") && src.contains("BindValue::Int"),
            "Value must marshal the scalar: {src}"
        );
        // Named-argument notation keeps a middle omission legal.
        assert!(
            src.contains("format!(\"p_a => :{__n}\")"),
            "defaulted call must use named-argument notation: {src}"
        );
        // Dynamic block is composed at runtime, not as a static literal.
        assert!(
            src.contains("let __block = format!(\"BEGIN hr.demo_pkg.proc_with_default("),
            "block must be built dynamically: {src}"
        );
    }

    #[test]
    fn defaulted_nullable_param_is_defaulted_option() {
        let r = RoutineBinding {
            name: "p".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![defaulted_param("p_a", "String", ParameterMode::In, true)],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("p_a: Defaulted<Option<String>>"),
            "nullable + defaulted must be Defaulted<Option<T>>: {src}"
        );
    }

    #[test]
    fn non_defaulted_routine_keeps_static_layout() {
        // Routines with no defaulted params must keep the original static
        // bind layout (positional binds, static vec!), unchanged.
        let r = RoutineBinding {
            name: "plain".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![param("p_a", "i64", ParameterMode::In, false)],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("let __args: Vec<RoutineArg> = vec!["),
            "non-defaulted routine must keep the static vec! layout: {src}"
        );
        assert!(
            !src.contains("Defaulted::"),
            "non-defaulted routine must not reference Defaulted: {src}"
        );
        assert!(
            src.contains("BEGIN hr.demo_pkg.plain(:1); END;"),
            "non-defaulted block stays positional and static: {src}"
        );
    }

    #[test]
    fn omitted_inout_default_is_a_typed_error_not_misaligned() {
        // An IN OUT defaulted param surfaces as Defaulted<T>, but omitting
        // it has no output to read back — the wrapper must fail closed with
        // a typed error rather than silently mis-aligning the return tuple.
        let r = RoutineBinding {
            name: "io".into(),
            kind: RoutineKind::Procedure,
            parameters: vec![defaulted_param("p_io", "i64", ParameterMode::InOut, false)],
            return_type: None,
            autonomous_transaction: false,
        };
        let src = emit_wrappers(&plan(vec![r]));
        assert!(
            src.contains("p_io: Defaulted<i64>"),
            "IN OUT defaulted must surface as Defaulted<T>: {src}"
        );
        assert!(
            src.contains("BINDING_OMIT_INOUT"),
            "omitting an IN OUT must be a typed error: {src}"
        );
    }

    // A hand-mirrored copy of exactly what `emit_routine_body_dynamic`
    // produces for `proc_with_default(p_a IN NUMBER DEFAULT 5)`. Compiling
    // it proves the emitted Rust is valid; running it against a stub
    // executor proves the three Defaulted states bind correctly. This is
    // the behavioral teeth behind the string assertions above.
    mod generated_shape {
        use crate::executor::{BindValue, ExecutionError, OracleExecutor, Row, RoutineArg};
        use crate::Defaulted;

        /// Records the block + args the wrapper handed the executor.
        #[derive(Default)]
        struct RecordingExecutor {
            last_block: std::cell::RefCell<String>,
            last_args: std::cell::RefCell<Vec<RoutineArg>>,
        }
        impl OracleExecutor for RecordingExecutor {
            fn execute(&self, _sql: &str, _binds: &[BindValue]) -> Result<u64, ExecutionError> {
                Ok(0)
            }
            fn query(&self, _sql: &str, _binds: &[BindValue]) -> Result<Vec<Row>, ExecutionError> {
                Ok(vec![])
            }
            fn call_routine(
                &self,
                plsql: &str,
                args: &[RoutineArg],
            ) -> Result<Vec<BindValue>, ExecutionError> {
                *self.last_block.borrow_mut() = plsql.to_string();
                *self.last_args.borrow_mut() = args.to_vec();
                Ok(vec![])
            }
        }

        // VERBATIM emitter output for proc_with_default — keep in lockstep
        // with emit_routine_body_dynamic. The emitter marshals every IN
        // value with `.clone()` because it is generic over Copy and
        // non-Copy types alike (e.g. String); cloning the Copy `i64` here
        // is the faithful generated shape, so silence the Copy lint.
        #[allow(clippy::clone_on_copy)]
        pub fn proc_with_default(
            executor: &mut impl OracleExecutor,
            p_a: Defaulted<i64>,
        ) -> Result<(), ExecutionError> {
            let mut __args: Vec<RoutineArg> = Vec::new();
            let mut __call: Vec<String> = Vec::new();
            let mut __slot: u32 = 1;
            match &p_a {
                Defaulted::Omit => {}
                Defaulted::Null => {
                    let __n = __slot;
                    __slot += 1;
                    __call.push(format!("p_a => :{__n}"));
                    __args.push(RoutineArg::In(BindValue::Null));
                }
                Defaulted::Value(__v) => {
                    let __n = __slot;
                    __slot += 1;
                    __call.push(format!("p_a => :{__n}"));
                    __args.push(RoutineArg::In(BindValue::Int((__v).clone())));
                }
            }
            let _ = __slot;
            let __block =
                format!("BEGIN hr.demo_pkg.proc_with_default({}); END;", __call.join(", "));
            let __out = executor.call_routine(&__block, &__args)?;
            let _ = __out;
            Ok(())
        }

        #[test]
        fn omit_binds_nothing_and_lets_server_default() {
            let mut exec = RecordingExecutor::default();
            proc_with_default(&mut exec, Defaulted::Omit).unwrap();
            assert!(
                exec.last_args.borrow().is_empty(),
                "Omit must bind no slot so the server evaluates the default"
            );
            assert_eq!(
                *exec.last_block.borrow(),
                "BEGIN hr.demo_pkg.proc_with_default(); END;",
                "Omit drops the argument entirely"
            );
        }

        #[test]
        fn null_binds_explicit_null_distinct_from_omit() {
            let mut exec = RecordingExecutor::default();
            proc_with_default(&mut exec, Defaulted::Null).unwrap();
            assert_eq!(
                *exec.last_args.borrow(),
                vec![RoutineArg::In(BindValue::Null)],
                "Null binds an explicit NULL, not the default"
            );
            assert_eq!(
                *exec.last_block.borrow(),
                "BEGIN hr.demo_pkg.proc_with_default(p_a => :1); END;"
            );
        }

        #[test]
        fn value_marshals_the_supplied_scalar() {
            let mut exec = RecordingExecutor::default();
            proc_with_default(&mut exec, Defaulted::Value(42)).unwrap();
            assert_eq!(
                *exec.last_args.borrow(),
                vec![RoutineArg::In(BindValue::Int(42))]
            );
            assert_eq!(
                *exec.last_block.borrow(),
                "BEGIN hr.demo_pkg.proc_with_default(p_a => :1); END;"
            );
        }
    }
}
