//! `plsql post-pr-comment` subcommand library.
//!
//! Reads a [`PrCommentEnvelope`] and
//! returns a `PostPrCommentRequest` describing the platform-specific
//! HTTP call needed to land the comment idempotently. We do NOT make
//! the network call in this crate — the binary wrapper is responsible
//! for the IO. This separation keeps the library pure-Rust + dep-light
//! (no `reqwest` / `hyper`) and the binary single-purpose.
//!
//! Idempotency contract: every comment carries the
//! `html_marker` from PrCommentEnvelope; the adapter looks for that
//! marker in existing PR comments and either creates or edits
//! depending on whether a match is found.

use serde::{Deserialize, Serialize};

use crate::gate::PrCommentEnvelope;

/// Supported PR-comment platforms.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Platform {
    GitHub,
    GitLab,
}

/// Concrete instruction the binary wrapper uses to talk to the
/// platform API. Captures everything the wrapper needs except the
/// auth token (which the wrapper reads from the environment so it
/// never lands in a log).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct PostPrCommentRequest {
    pub platform: Platform,
    /// Owner/org segment (e.g. `acme-corp`).
    pub owner: String,
    /// Repository or project segment (e.g. `billing-db`).
    pub repository: String,
    /// PR / MR number.
    pub pull_request: u64,
    /// HTTP method (`POST` for create, `PATCH` for edit).
    pub method: String,
    /// Fully-qualified API URL.
    pub url: String,
    /// Request body — the exact JSON the platform expects.
    pub body_json: serde_json::Value,
    /// Stable HTML marker the adapter uses to recognise its own prior
    /// comment on repeat invocations.
    pub html_marker: String,
}

/// Platform-specific repository coordinates, kept small so callers
/// can pass a struct rather than four positional args.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PrCoordinates {
    pub platform: Platform,
    pub owner: String,
    pub repository: String,
    pub pull_request: u64,
    /// Existing comment id if the adapter has already found a match
    /// for `html_marker` (turns a CREATE into an EDIT). When None,
    /// the request is a CREATE.
    pub existing_comment_id: Option<u64>,
}

/// Find the existing comment (if any) whose body carries the given
/// `html_marker`. Walks the iterator
/// of `(comment_id, body)` tuples and returns the first match. Used
/// by the binary wrapper to turn a CREATE into an EDIT for idempotent
/// updates — one plsql-cicd comment per PR, edited in place.
///
/// The matcher is intentionally simple: a substring check on
/// `html_marker`. The marker is generated by [`PrCommentEnvelope`]
/// and prefixed onto every body in [`build_request`], so a substring
/// hit is reliable. The marker carries the schema version
/// (`<!-- plsql-cicd:gate v1 -->`) so a future schema bump shifts the
/// marker and orphans the old comment — desired behavior when the
/// shape changes.
#[must_use]
pub fn find_existing_comment<I, S>(html_marker: &str, comments: I) -> Option<u64>
where
    I: IntoIterator<Item = (u64, S)>,
    S: AsRef<str>,
{
    comments
        .into_iter()
        .find_map(|(id, body)| body.as_ref().contains(html_marker).then_some(id))
}

/// Build a [`PostPrCommentRequest`] for the given envelope at the
/// given coordinates. The shape is deterministic — same inputs
/// produce byte-identical output.
#[must_use]
pub fn build_request(envelope: &PrCommentEnvelope, coords: &PrCoordinates) -> PostPrCommentRequest {
    let body_with_marker = format!(
        "{marker}\n{body}",
        marker = envelope.pr_comment.html_marker,
        body = envelope.pr_comment.body_md
    );
    let body_json = match coords.platform {
        Platform::GitHub => serde_json::json!({ "body": body_with_marker }),
        Platform::GitLab => serde_json::json!({ "body": body_with_marker }),
    };
    let (method, url) = match (coords.platform, coords.existing_comment_id) {
        (Platform::GitHub, None) => (
            String::from("POST"),
            format!(
                "https://api.github.com/repos/{owner}/{repo}/issues/{pr}/comments",
                owner = coords.owner,
                repo = coords.repository,
                pr = coords.pull_request,
            ),
        ),
        (Platform::GitHub, Some(id)) => (
            String::from("PATCH"),
            format!(
                "https://api.github.com/repos/{owner}/{repo}/issues/comments/{id}",
                owner = coords.owner,
                repo = coords.repository,
            ),
        ),
        (Platform::GitLab, None) => (
            String::from("POST"),
            format!(
                "https://gitlab.com/api/v4/projects/{owner}%2F{repo}/merge_requests/{pr}/notes",
                owner = coords.owner,
                repo = coords.repository,
                pr = coords.pull_request,
            ),
        ),
        (Platform::GitLab, Some(id)) => (
            String::from("PUT"),
            format!(
                "https://gitlab.com/api/v4/projects/{owner}%2F{repo}/merge_requests/{pr}/notes/{id}",
                owner = coords.owner,
                repo = coords.repository,
                pr = coords.pull_request,
            ),
        ),
    };
    PostPrCommentRequest {
        platform: coords.platform,
        owner: coords.owner.clone(),
        repository: coords.repository.clone(),
        pull_request: coords.pull_request,
        method,
        url,
        body_json,
        html_marker: envelope.pr_comment.html_marker.clone(),
    }
}

// `PLSQL-CICD-022` (oracle-lcxu): doctor check on PR-integration
// health. Stable JSON shape that surfaces three signals the operator
// cares about: token presence, payload schema version, and whether
// the last posted comment matches the current marker shape.
const PR_DOCTOR_SCHEMA_ID: &str = "plsql.cicd.pr_integration_doctor";
const PR_DOCTOR_SCHEMA_VERSION: u32 = 1;

/// Snapshot of the operator's PR-integration health.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct PrIntegrationDoctorReport {
    pub schema_id: String,
    pub schema_version: u32,
    pub platform: Platform,
    /// Is an auth token configured for this platform? Doctor never
    /// reads the token itself — just the env var presence.
    pub token_present: bool,
    /// Name of the env var the doctor checked.
    pub token_env_var: String,
    /// Schema version of the [`PrCommentEnvelope`] the doctor is
    /// running against. Drift here means the operator's tooling is
    /// emitting a payload the comment poster doesn't recognise.
    pub envelope_schema_version: u32,
    /// `html_marker` from the envelope, so the operator can grep
    /// existing PR comments for it manually.
    pub html_marker: String,
    /// `pass` when a matching comment was found on the target PR (or
    /// when the doctor was run without `last_comment_check`); `fail`
    /// when explicitly checked and no marker hit landed.
    pub last_comment_posted: PrCommentCheck,
    /// Overall posture — `Healthy` when token + envelope are ok and
    /// the last-comment check passes or wasn't run. `Caution` when
    /// the last-comment check explicitly failed. `Unknown` when the
    /// auth token isn't configured.
    pub posture: PrPosture,
    /// One-line operator hints.
    pub remediation_hints: Vec<String>,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PrCommentCheck {
    /// Last-comment lookup was not performed.
    #[default]
    NotChecked,
    /// Looked up existing comments and found a match for the marker.
    Found,
    /// Looked up existing comments and found no match.
    NotFound,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PrPosture {
    Healthy,
    #[default]
    Caution,
    Unknown,
}

/// Inputs for [`pr_integration_doctor`]. The caller decides whether
/// to perform the last-comment lookup; for an offline `doctor`
/// invocation only token presence + envelope schema are checked.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PrIntegrationDoctorInputs<'a> {
    pub platform: Platform,
    pub token_env_value: Option<&'a str>,
    pub envelope: &'a PrCommentEnvelope,
    pub last_comment_check: PrCommentCheck,
}

/// Compute the doctor report.
#[must_use]
pub fn pr_integration_doctor(inputs: &PrIntegrationDoctorInputs<'_>) -> PrIntegrationDoctorReport {
    let token_env_var = match inputs.platform {
        Platform::GitHub => "PLSQL_GH_TOKEN",
        Platform::GitLab => "PLSQL_GL_TOKEN",
    };
    let token_present = inputs
        .token_env_value
        .map(|v| !v.trim().is_empty())
        .unwrap_or(false);

    let posture = classify_pr_posture(token_present, inputs.last_comment_check);
    let mut remediation_hints = Vec::new();
    if !token_present {
        remediation_hints.push(format!(
            "{token_env_var} is not set — the post-pr-comment adapter will refuse to call the {platform:?} API.",
            platform = inputs.platform,
        ));
    }
    if matches!(inputs.last_comment_check, PrCommentCheck::NotFound) {
        remediation_hints.push(format!(
            "No existing comment carries the marker `{}` — the next run will CREATE rather than EDIT.",
            inputs.envelope.pr_comment.html_marker,
        ));
    }
    if inputs.envelope.schema_version != 1 {
        remediation_hints.push(format!(
            "PrCommentEnvelope schema version is {} (expected 1) — the comment poster may not recognise the payload.",
            inputs.envelope.schema_version,
        ));
    }

    PrIntegrationDoctorReport {
        schema_id: PR_DOCTOR_SCHEMA_ID.into(),
        schema_version: PR_DOCTOR_SCHEMA_VERSION,
        platform: inputs.platform,
        token_present,
        token_env_var: token_env_var.into(),
        envelope_schema_version: inputs.envelope.schema_version,
        html_marker: inputs.envelope.pr_comment.html_marker.clone(),
        last_comment_posted: inputs.last_comment_check,
        posture,
        remediation_hints,
    }
}

fn classify_pr_posture(token_present: bool, last_comment_check: PrCommentCheck) -> PrPosture {
    if !token_present {
        return PrPosture::Unknown;
    }
    match last_comment_check {
        PrCommentCheck::Found | PrCommentCheck::NotChecked => PrPosture::Healthy,
        PrCommentCheck::NotFound => PrPosture::Caution,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gate::{GatePolicy, render_pr_comment, run_gate};
    use crate::{InvalidationPrediction, PredictMode};

    fn envelope() -> PrCommentEnvelope {
        let pred = InvalidationPrediction {
            mode: PredictMode::SourceOnly,
            predicted_invalidations: vec![],
            ..Default::default()
        };
        let decision = run_gate(&pred, &GatePolicy::default());
        render_pr_comment(&decision)
    }

    fn gh_coords(existing: Option<u64>) -> PrCoordinates {
        PrCoordinates {
            platform: Platform::GitHub,
            owner: "acme".into(),
            repository: "billing".into(),
            pull_request: 42,
            existing_comment_id: existing,
        }
    }

    fn gl_coords(existing: Option<u64>) -> PrCoordinates {
        PrCoordinates {
            platform: Platform::GitLab,
            owner: "acme".into(),
            repository: "billing".into(),
            pull_request: 42,
            existing_comment_id: existing,
        }
    }

    #[test]
    fn github_create_request_posts_to_issues_comments() {
        let req = build_request(&envelope(), &gh_coords(None));
        assert_eq!(req.method, "POST");
        assert_eq!(
            req.url,
            "https://api.github.com/repos/acme/billing/issues/42/comments"
        );
        let body = req.body_json["body"].as_str().unwrap();
        assert!(body.starts_with("<!-- plsql-cicd:gate v"));
    }

    #[test]
    fn github_edit_request_patches_issues_comment_id() {
        let req = build_request(&envelope(), &gh_coords(Some(99)));
        assert_eq!(req.method, "PATCH");
        assert_eq!(
            req.url,
            "https://api.github.com/repos/acme/billing/issues/comments/99"
        );
    }

    #[test]
    fn gitlab_create_request_posts_to_mr_notes() {
        let req = build_request(&envelope(), &gl_coords(None));
        assert_eq!(req.method, "POST");
        assert_eq!(
            req.url,
            "https://gitlab.com/api/v4/projects/acme%2Fbilling/merge_requests/42/notes"
        );
    }

    #[test]
    fn gitlab_edit_request_puts_note_id() {
        let req = build_request(&envelope(), &gl_coords(Some(99)));
        assert_eq!(req.method, "PUT");
        assert_eq!(
            req.url,
            "https://gitlab.com/api/v4/projects/acme%2Fbilling/merge_requests/42/notes/99"
        );
    }

    #[test]
    fn body_carries_html_marker_for_idempotent_edit() {
        let env = envelope();
        let req = build_request(&env, &gh_coords(None));
        let body = req.body_json["body"].as_str().unwrap();
        assert!(body.starts_with(&env.pr_comment.html_marker));
        assert_eq!(req.html_marker, env.pr_comment.html_marker);
    }

    #[test]
    fn request_is_deterministic_across_calls() {
        let env = envelope();
        let a = build_request(&env, &gh_coords(None));
        let b = build_request(&env, &gh_coords(None));
        assert_eq!(a, b);
    }

    // -----------------------------------------------------------------
    // PLSQL-CICD-016 (oracle-usq7) — idempotent find-existing tests.
    // -----------------------------------------------------------------

    #[test]
    fn find_existing_comment_returns_first_match_by_marker() {
        let marker = "<!-- plsql-cicd:gate v1 -->";
        let comments = vec![
            (10, "unrelated comment".to_string()),
            (11, format!("{marker}\n## plsql cicd gate: PASS\n")),
            (12, format!("{marker}\n## stale duplicate")),
        ];
        assert_eq!(find_existing_comment(marker, comments), Some(11));
    }

    #[test]
    fn find_existing_comment_returns_none_when_no_match() {
        let marker = "<!-- plsql-cicd:gate v1 -->";
        let comments = vec![
            (10, "unrelated".to_string()),
            (11, "also unrelated".to_string()),
        ];
        assert_eq!(find_existing_comment(marker, comments), None);
    }

    #[test]
    fn find_existing_comment_ignores_version_skewed_markers() {
        // A v2 marker should NOT match a v1 lookup — the version bump
        // is part of the marker on purpose so a schema shift orphans
        // the old comment.
        let v1 = "<!-- plsql-cicd:gate v1 -->";
        let comments = vec![(10, "<!-- plsql-cicd:gate v2 -->\nbody".to_string())];
        assert_eq!(find_existing_comment(v1, comments), None);
    }

    #[test]
    fn find_existing_comment_works_with_borrowed_strs() {
        // The signature accepts AsRef<str> so callers can pass
        // (&[(u64, &str)]) or (&[(u64, String)]) without ceremony.
        let marker = "marker";
        let bodies = [(1u64, "no"), (2, "marker here"), (3, "marker again")];
        assert_eq!(find_existing_comment(marker, bodies), Some(2));
    }

    // -----------------------------------------------------------------
    // PLSQL-CICD-022 (oracle-lcxu) — PR-integration doctor tests.
    // -----------------------------------------------------------------

    fn doctor_inputs<'a>(
        platform: Platform,
        token: Option<&'a str>,
        envelope: &'a PrCommentEnvelope,
        check: PrCommentCheck,
    ) -> PrIntegrationDoctorInputs<'a> {
        PrIntegrationDoctorInputs {
            platform,
            token_env_value: token,
            envelope,
            last_comment_check: check,
        }
    }

    #[test]
    fn doctor_healthy_when_token_present_and_check_skipped() {
        let env = envelope();
        let report = pr_integration_doctor(&doctor_inputs(
            Platform::GitHub,
            Some("ghp_redacted"),
            &env,
            PrCommentCheck::NotChecked,
        ));
        assert_eq!(report.posture, PrPosture::Healthy);
        assert!(report.token_present);
        assert_eq!(report.token_env_var, "PLSQL_GH_TOKEN");
        assert!(report.remediation_hints.is_empty());
    }

    #[test]
    fn doctor_unknown_when_token_missing() {
        let env = envelope();
        let report = pr_integration_doctor(&doctor_inputs(
            Platform::GitLab,
            None,
            &env,
            PrCommentCheck::NotChecked,
        ));
        assert_eq!(report.posture, PrPosture::Unknown);
        assert!(!report.token_present);
        assert!(
            report
                .remediation_hints
                .iter()
                .any(|h| h.contains("PLSQL_GL_TOKEN"))
        );
    }

    #[test]
    fn doctor_caution_when_last_comment_check_failed() {
        let env = envelope();
        let report = pr_integration_doctor(&doctor_inputs(
            Platform::GitHub,
            Some("ghp_redacted"),
            &env,
            PrCommentCheck::NotFound,
        ));
        assert_eq!(report.posture, PrPosture::Caution);
        assert_eq!(report.last_comment_posted, PrCommentCheck::NotFound);
        assert!(
            report
                .remediation_hints
                .iter()
                .any(|h| h.contains("CREATE rather than EDIT"))
        );
    }

    #[test]
    fn doctor_healthy_when_last_comment_was_found() {
        let env = envelope();
        let report = pr_integration_doctor(&doctor_inputs(
            Platform::GitHub,
            Some("ghp_redacted"),
            &env,
            PrCommentCheck::Found,
        ));
        assert_eq!(report.posture, PrPosture::Healthy);
        assert_eq!(report.last_comment_posted, PrCommentCheck::Found);
    }

    #[test]
    fn doctor_carries_envelope_marker_and_schema_version() {
        let env = envelope();
        let report = pr_integration_doctor(&doctor_inputs(
            Platform::GitHub,
            Some("ghp_redacted"),
            &env,
            PrCommentCheck::NotChecked,
        ));
        assert_eq!(report.envelope_schema_version, env.schema_version);
        assert_eq!(report.html_marker, env.pr_comment.html_marker);
    }

    #[test]
    fn doctor_schema_id_and_version_pinned() {
        let env = envelope();
        let report = pr_integration_doctor(&doctor_inputs(
            Platform::GitHub,
            Some("t"),
            &env,
            PrCommentCheck::NotChecked,
        ));
        assert_eq!(report.schema_id, "plsql.cicd.pr_integration_doctor");
        assert_eq!(report.schema_version, 1);
    }
}
