//! `verify <changeset>` against a scratch schema / disposable Oracle container.
//!
//! # Purpose
//!
//! Applies a changeset's DDL statements to a fresh, throwaway Oracle schema
//! (`VERIFY_T_<random>`) and reports per-statement success or failure. The
//! schema is created immediately before verification begins and dropped
//! immediately after — even on panic, via the [`ScratchSchemaGuard`] RAII
//! helper.
//!
//! # ⚠️  NO ROLLBACK GUARANTEE
//!
//! **DDL in Oracle implicitly commits.** There is no transaction boundary that
//! can atomically roll back a failed changeset. Each statement that succeeds
//! permanently modifies the scratch schema's state for the remainder of the
//! verification run. This is the correct behaviour — the scratch schema is
//! disposable — but callers must understand that:
//!
//! - A changeset that fails mid-way will have applied all statements *up to*
//!   the failure point. Subsequent statements are not attempted.
//! - The scratch schema is dropped in teardown regardless of success or
//!   failure, so the mid-run state is not observable after the run completes.
//! - The final report lists each statement's outcome individually so the
//!   operator knows exactly where the changeset diverged.
//!
//! This semantic is documented in the `--help` text of the `verify` command as
//! "verify applies DDL to a throwaway schema; Oracle DDL auto-commits —
//! verification is destructive within the scratch schema and cannot be rolled
//! back if it fails mid-changeset."
//!
//! # In-place guard
//!
//! By default `verify` refuses to run against a non-scratch schema. Passing a
//! target that does not look like `VERIFY_T_*` is rejected with
//! [`VerifyError::InPlaceVerificationRefused`] unless `allow_in_place` is
//! explicitly set to `true` in [`VerifyOptions`]. The interactive confirmation
//! flow for `--dangerously-verify-in-place` lives in the CLI driver — this
//! module exposes the boolean seam so the driver can wire in without
//! touching this file.
//!
//! # Scratch schema naming
//!
//! Schema names are generated by [`scratch_schema_name`]. They take the form
//! `VERIFY_T_<pid>` where `<pid>` is the current process id, giving sufficient
//! isolation for a single concurrent verify run per process. The `VERIFY_T_`
//! prefix is the isolation contract: `verify` will only create and drop schemas
//! whose names match this prefix.
//!
//! ## /oracle evidence
//!
//! * Oracle DDL auto-commit behaviour is documented in the Oracle Database
//!   Concepts Guide: "DDL statements are not transactional in Oracle Database.
//!   Every DDL statement is implicitly preceded by a COMMIT and followed by
//!   a COMMIT or ROLLBACK."
//! * `CREATE USER … IDENTIFIED BY …` + `GRANT CREATE SESSION TO …` +
//!   `DROP USER … CASCADE` are the canonical DBA-level schema lifecycle
//!   verbs used throughout the Oracle SYSTEM / DBA playbook.

use std::fmt;

use plsql_catalog::OracleConnection;
use thiserror::Error;
use tracing::instrument;

use crate::CicdError;

// ── Errors ────────────────────────────────────────────────────────────────────

/// Errors emitted by the `verify` pipeline.
#[derive(Debug, Error)]
pub enum VerifyError {
    /// `verify` refused to run against a schema that does not start with
    /// `VERIFY_T_` because `allow_in_place` is `false`. Use the
    /// `--dangerously-verify-in-place` flag to enable this
    /// after interactive confirmation.
    #[error(
        "verify refused to run against schema `{schema}` — it does not look like a scratch \
         schema (expected `VERIFY_T_*`). Pass `--dangerously-verify-in-place` to override \
         (requires interactive confirmation, oracle-q2o8)."
    )]
    InPlaceVerificationRefused { schema: String },

    /// `--dangerously-verify-in-place` was passed but the operator did not
    /// retype the connected schema name verbatim at the interactive
    /// confirmation prompt. The destructive in-place path stays disabled.
    #[error(
        "in-place verification NOT confirmed: operator typed `{got}` but the connected schema \
         is `{expected}` — they must match exactly. Aborting (in-place stays disabled)."
    )]
    InPlaceConfirmationMismatch { expected: String, got: String },

    /// A scratch schema name failed the `VERIFY_T_` prefix check. This is
    /// an internal safety guard — callers should use [`scratch_schema_name`].
    #[error("generated scratch schema name `{name}` does not start with `VERIFY_T_`")]
    InvalidScratchSchemaName { name: String },

    /// The scratch-user password failed validation before being interpolated
    /// into the `CREATE USER ... IDENTIFIED BY "..."` DDL. The password is
    /// quoted into a single DDL statement, so a stray `"` (or other
    /// out-of-allowlist character) would corrupt the statement and surface as
    /// a confusing ORA error rather than a clear rejection. We reject up front
    /// instead of escaping: a `"` in an operator-chosen password almost
    /// certainly signals a misconfiguration.
    #[error("invalid scratch-user password: {reason}")]
    InvalidScratchPassword { reason: String },

    /// The changeset has no SQL statements to apply.
    #[error("changeset has no SQL statements to verify")]
    EmptyChangeset,

    /// An Oracle operation required to set up or tear down the scratch schema
    /// failed.
    #[error("scratch schema lifecycle error: {message}")]
    SchemaLifecycle { message: String },

    /// Wraps a [`CicdError`] that surfaced during statement execution.
    #[error("cicd error during verify: {0}")]
    Cicd(#[from] CicdError),
}

// ── Scratch schema naming ─────────────────────────────────────────────────────

/// Generate a scratch schema name for this process.
///
/// The name is `VERIFY_T_<pid>`, upper-cased and Oracle-identifier-safe. The
/// `VERIFY_T_` prefix is the isolation contract recognised by the schema
/// lifecycle helpers: they will only create or drop schemas whose names start
/// with this prefix.
///
/// Oracle identifiers are limited to 30 bytes in older editions and 128 in
/// 23ai. `VERIFY_T_<u32>` — at most `VERIFY_T_` (9) + 10 digits = 19 chars —
/// is well within either limit.
#[must_use]
pub fn scratch_schema_name() -> String {
    scratch_schema_name_for_pid(std::process::id())
}

/// Inner helper, testable with an arbitrary pid.
#[must_use]
pub fn scratch_schema_name_for_pid(pid: u32) -> String {
    format!("VERIFY_T_{pid}")
}

/// Return `true` iff `name` is a valid scratch schema name (case-insensitive
/// `VERIFY_T_` prefix). `verify` will only create or drop schemas that pass
/// this check.
#[must_use]
pub fn is_scratch_schema(name: &str) -> bool {
    name.to_ascii_uppercase().starts_with("VERIFY_T_")
}

// ── Changeset DDL input ───────────────────────────────────────────────────────

/// One DDL statement to apply during a `verify` run.
///
/// The `sql` field must not include a trailing semicolon — the Oracle driver
/// sends each statement individually. Comments and whitespace are allowed.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct VerifyStatement {
    /// Monotonically increasing ordinal (1-based). Matches the ordinal in the
    /// upstream `DeploymentStatement` when `verify` is driven from a
    /// `DeploymentPlan`.
    pub ordinal: u32,
    /// SQL text without trailing semicolon.
    pub sql: String,
    /// Human-readable label for the statement (e.g. `"CREATE TABLE ORDERS"`).
    pub label: Option<String>,
}

/// A changeset expressed as a flat, ordered list of DDL statements to apply to
/// a scratch schema.
///
/// Construct via [`VerifyChangeset::new`] or from an iterator of statements.
#[derive(Clone, Debug, Default)]
pub struct VerifyChangeset {
    pub statements: Vec<VerifyStatement>,
}

impl VerifyChangeset {
    /// Construct from an ordered list of `(ordinal, sql)` pairs.
    #[must_use]
    pub fn new(statements: impl IntoIterator<Item = (u32, String)>) -> Self {
        Self {
            statements: statements
                .into_iter()
                .map(|(ordinal, sql)| VerifyStatement {
                    ordinal,
                    sql,
                    label: None,
                })
                .collect(),
        }
    }

    /// Construct from an ordered list of `(ordinal, sql, label)` triples.
    #[must_use]
    pub fn with_labels(
        statements: impl IntoIterator<Item = (u32, String, Option<String>)>,
    ) -> Self {
        Self {
            statements: statements
                .into_iter()
                .map(|(ordinal, sql, label)| VerifyStatement {
                    ordinal,
                    sql,
                    label,
                })
                .collect(),
        }
    }

    /// `true` when there are no statements to apply.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.statements.is_empty()
    }
}

// ── Per-statement outcome ─────────────────────────────────────────────────────

/// Outcome of applying a single DDL statement during verification.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum StatementOutcome {
    /// The statement executed without error.
    Ok,
    /// The statement failed with the given Oracle error message.
    ///
    /// **Because DDL implicitly commits, all prior statements in the
    /// changeset have already been applied and cannot be rolled back.**
    Failed { error: String },
    /// The statement was not attempted because a previous statement failed.
    Skipped,
}

impl fmt::Display for StatementOutcome {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Ok => write!(f, "OK"),
            Self::Failed { error } => write!(f, "FAILED: {error}"),
            Self::Skipped => write!(f, "SKIPPED"),
        }
    }
}

/// One row in a [`VerifyReport`].
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct VerifyReportRow {
    pub ordinal: u32,
    pub label: Option<String>,
    pub outcome: StatementOutcome,
}

// ── Verification report ───────────────────────────────────────────────────────

/// The result of a `verify` run.
///
/// `statements` lists every input statement in order with its outcome. The
/// overall run is [`VerifyReport::is_clean`] only when all statements
/// succeeded.
///
/// # ⚠️  No rollback guarantee
///
/// Each row whose `outcome` is [`StatementOutcome::Ok`] caused a DDL commit in
/// Oracle. If the run ends with one or more `Failed` rows, the scratch schema
/// reflects the state after the last successful DDL — the failed statement and
/// all subsequent statements were not applied. The scratch schema is dropped
/// unconditionally in teardown.
#[derive(Clone, Debug, Default)]
pub struct VerifyReport {
    /// Name of the scratch schema used for this run.
    pub schema: String,
    /// Per-statement outcomes, in input order.
    pub rows: Vec<VerifyReportRow>,
}

impl VerifyReport {
    /// `true` iff every statement in the changeset succeeded.
    #[must_use]
    pub fn is_clean(&self) -> bool {
        self.rows
            .iter()
            .all(|r| matches!(r.outcome, StatementOutcome::Ok))
    }

    /// Number of statements that succeeded.
    #[must_use]
    pub fn ok_count(&self) -> usize {
        self.rows
            .iter()
            .filter(|r| matches!(r.outcome, StatementOutcome::Ok))
            .count()
    }

    /// Number of statements that failed.
    #[must_use]
    pub fn failed_count(&self) -> usize {
        self.rows
            .iter()
            .filter(|r| matches!(r.outcome, StatementOutcome::Failed { .. }))
            .count()
    }

    /// Number of statements that were skipped (because a prior statement
    /// failed).
    #[must_use]
    pub fn skipped_count(&self) -> usize {
        self.rows
            .iter()
            .filter(|r| matches!(r.outcome, StatementOutcome::Skipped))
            .count()
    }

    /// Collect error messages for all failed rows, in ordinal order.
    #[must_use]
    pub fn failure_messages(&self) -> Vec<(u32, String)> {
        self.rows
            .iter()
            .filter_map(|r| {
                if let StatementOutcome::Failed { error } = &r.outcome {
                    Some((r.ordinal, error.clone()))
                } else {
                    None
                }
            })
            .collect()
    }
}

// ── Verify options ────────────────────────────────────────────────────────────

/// Options governing a single `verify` run.
#[derive(Clone, Debug, Default)]
pub struct VerifyOptions {
    /// When `false` (the default), `verify` refuses to run against any schema
    /// name that does not start with `VERIFY_T_`. Set to `true` only from the
    /// interactive `--dangerously-verify-in-place` gate.
    pub allow_in_place: bool,

    /// Override the scratch schema name. If `None`, [`scratch_schema_name`] is
    /// used. Must start with `VERIFY_T_` unless `allow_in_place` is `true`.
    pub schema_override: Option<String>,

    /// Password to use when creating the scratch user. Defaults to a safe
    /// generated value when `None`. SYSTEM must have `CREATE USER` privilege.
    pub scratch_user_password: Option<String>,
}

impl VerifyOptions {
    /// Resolve the effective schema name: `schema_override` if set, else the
    /// process-id-derived default.
    #[must_use]
    pub fn effective_schema(&self) -> String {
        self.schema_override
            .clone()
            .unwrap_or_else(scratch_schema_name)
    }

    /// Validate the effective schema and return it, or error if the guard
    /// would refuse to proceed.
    pub fn validated_schema(&self) -> Result<String, VerifyError> {
        let schema = self.effective_schema();
        if !self.allow_in_place && !is_scratch_schema(&schema) {
            return Err(VerifyError::InPlaceVerificationRefused {
                schema: schema.clone(),
            });
        }
        Ok(schema)
    }

    /// Effective password for the scratch user.
    #[must_use]
    pub fn effective_password(&self) -> String {
        self.scratch_user_password
            .clone()
            .unwrap_or_else(|| String::from("V3r1fyTmp#2026"))
    }
}

// ── In-place confirmation gate (PLSQL-CICD-005A / oracle-q2o8) ────────────────

/// Outcome of the `--dangerously-verify-in-place` interactive gate.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum InPlaceDecision {
    /// The flag was not passed — verify takes the safe scratch-schema path.
    /// `allow_in_place` stays `false`.
    NotRequested,
    /// The flag was passed AND the operator retyped the connected schema name
    /// verbatim. The caller may set `VerifyOptions.allow_in_place = true`.
    Confirmed,
}

/// Interactive safety gate for destructive in-place DDL verification.
///
/// `verify` runs against a throwaway `VERIFY_T_*` scratch schema by default;
/// DDL implicitly commits, so an in-place run against a real schema is
/// irreversible. This gate makes that path require *two independent signals*:
///
/// 1. the `--dangerously-verify-in-place` CLI flag (`flag_passed`), and
/// 2. the operator retyping the **connected schema name verbatim** at an
///    interactive prompt — defeating muscle-memory "yes/enter" confirmation.
///
/// I/O is injected (`prompt` reader + `out` writer) so the gate is fully
/// unit-testable without a TTY; the CLI passes stdin/stderr. The match is
/// exact after trimming a single trailing newline (the operator presses
/// Enter) — case, whitespace, and spelling must otherwise be identical.
///
/// Returns [`InPlaceDecision::Confirmed`] only on an exact match;
/// [`InPlaceDecision::NotRequested`] when the flag was absent; and
/// [`VerifyError::InPlaceConfirmationMismatch`] when the flag was present but
/// the typed text did not match (the caller MUST NOT set `allow_in_place`).
#[instrument(level = "trace", skip(read_line, out))]
pub fn confirm_in_place_verification<R, W>(
    flag_passed: bool,
    connected_schema: &str,
    mut read_line: R,
    mut out: W,
) -> Result<InPlaceDecision, VerifyError>
where
    R: FnMut() -> std::io::Result<String>,
    W: std::io::Write,
{
    if !flag_passed {
        return Ok(InPlaceDecision::NotRequested);
    }

    let _ = writeln!(
        out,
        "!! DANGER: in-place verification applies DDL directly to schema \
         `{connected_schema}`.\n\
         !! DDL auto-commits in Oracle — this is IRREVERSIBLE (no rollback).\n\
         To proceed, retype the connected schema name exactly: ",
    );

    let typed = read_line().map_err(|e| VerifyError::SchemaLifecycle {
        message: format!("could not read in-place confirmation input: {e}"),
    })?;
    // The operator presses Enter; strip exactly one trailing newline
    // (and its optional preceding CR for `\r\n` terminals).
    let typed = typed
        .strip_suffix('\n')
        .map_or(typed.as_str(), |s| s.strip_suffix('\r').unwrap_or(s));

    if typed == connected_schema {
        let _ = writeln!(out, "Confirmed. Proceeding with IN-PLACE verification.");
        Ok(InPlaceDecision::Confirmed)
    } else {
        Err(VerifyError::InPlaceConfirmationMismatch {
            expected: connected_schema.to_string(),
            got: typed.to_string(),
        })
    }
}

// ── Schema lifecycle (requires DBA / SYSTEM connection) ───────────────────────

/// RAII guard that drops the scratch schema on `Drop`, even on panic.
///
/// Dropping this guard will attempt to `DROP USER <schema> CASCADE`. If the
/// drop fails, the error is logged but not re-raised (since we are already in
/// teardown). Never construct a `ScratchSchemaGuard` around a non-`VERIFY_T_`
/// schema.
pub struct ScratchSchemaGuard<'a, C: OracleConnection> {
    schema: String,
    conn: &'a C,
    already_dropped: bool,
}

impl<'a, C: OracleConnection> ScratchSchemaGuard<'a, C> {
    /// Create the guard. The caller is responsible for having created the
    /// scratch schema already.
    ///
    /// # Panics
    ///
    /// Panics if `schema` does not start with `VERIFY_T_` — this is a
    /// hard defensive check that should never trigger in correct usage.
    #[must_use]
    pub fn new(schema: impl Into<String>, conn: &'a C) -> Self {
        let schema = schema.into();
        assert!(
            is_scratch_schema(&schema),
            "BUG: ScratchSchemaGuard created for non-scratch schema `{schema}`"
        );
        Self {
            schema,
            conn,
            already_dropped: false,
        }
    }

    /// Explicitly drop the schema. Returns the Oracle error if the drop
    /// fails; this is idempotent — calling `drop_now` after `Drop` has
    /// already fired is a no-op.
    pub fn drop_now(&mut self) -> Result<(), VerifyError> {
        if self.already_dropped {
            return Ok(());
        }
        self.already_dropped = true;
        let sql = format!("DROP USER {} CASCADE", self.schema);
        self.conn
            .execute(&sql, &[])
            .map(|_| ())
            .map_err(|e| VerifyError::SchemaLifecycle {
                message: format!("DROP USER {} CASCADE failed: {e}", self.schema),
            })
    }
}

impl<C: OracleConnection> Drop for ScratchSchemaGuard<'_, C> {
    fn drop(&mut self) {
        if self.already_dropped {
            return;
        }
        self.already_dropped = true;
        let sql = format!("DROP USER {} CASCADE", self.schema);
        // Best-effort — we are in Drop, cannot propagate errors.
        if let Err(e) = self.conn.execute(&sql, &[]) {
            tracing::error!(
                schema = %self.schema,
                error = %e,
                "ScratchSchemaGuard teardown: DROP USER failed (schema may persist — manual cleanup required)"
            );
        }
    }
}

// ── Schema lifecycle helpers ──────────────────────────────────────────────────

/// Maximum scratch-user password length we accept. Oracle (pre-12.2) caps
/// passwords at 30 bytes; 12.2+ allows 128. We use the larger limit — every
/// allowlisted character is a single ASCII byte, so length equals byte count.
const MAX_SCRATCH_PASSWORD_LEN: usize = 128;

/// Validate a scratch-user password before it is interpolated into the
/// `CREATE USER ... IDENTIFIED BY "..."` DDL.
///
/// The password is double-quoted into a *single* DDL statement. A stray `"`
/// would close the quoted literal early and corrupt the statement, surfacing
/// as a confusing ORA error rather than a clear rejection. Rather than escape,
/// we reject anything outside a conservative allowlist — a `"` (or shell/SQL
/// metacharacter) in an operator-chosen password almost always signals a
/// misconfiguration, so explicit rejection is the safer, clearer behaviour.
///
/// Accepts only `[A-Za-z0-9#_$.+-]`, rejects empty and over-length
/// (> [`MAX_SCRATCH_PASSWORD_LEN`]) passwords.
///
/// # Errors
///
/// Returns [`VerifyError::InvalidScratchPassword`] if the password is empty,
/// too long, or contains a disallowed character.
pub fn validate_scratch_password(password: &str) -> Result<(), VerifyError> {
    if password.is_empty() {
        return Err(VerifyError::InvalidScratchPassword {
            reason: "password must not be empty".to_string(),
        });
    }
    if password.len() > MAX_SCRATCH_PASSWORD_LEN {
        return Err(VerifyError::InvalidScratchPassword {
            reason: format!(
                "password is {} bytes; must be at most {MAX_SCRATCH_PASSWORD_LEN}",
                password.len()
            ),
        });
    }
    if let Some(bad) = password
        .chars()
        .find(|c| !matches!(c, 'A'..='Z' | 'a'..='z' | '0'..='9' | '#' | '_' | '$' | '.' | '+' | '-'))
    {
        return Err(VerifyError::InvalidScratchPassword {
            reason: format!(
                "password contains disallowed character `{bad}` — only [A-Za-z0-9#_$.+-] are permitted"
            ),
        });
    }
    Ok(())
}

/// Create the scratch schema as a new Oracle user.
///
/// Requires `conn` to have `CREATE USER`, `DROP USER`, and `GRANT` privileges
/// (i.e. be connected as SYSTEM or a DBA account).
///
/// Grants the minimum set of privileges needed to execute the changeset DDL
/// inside the scratch schema:
/// - `CREATE SESSION` (mandatory to connect)
/// - `CREATE TABLE`, `CREATE VIEW`, `CREATE PROCEDURE`, `CREATE SEQUENCE`,
///   `CREATE TRIGGER`, `CREATE INDEX` (needed for common DDL statement kinds)
/// - `UNLIMITED TABLESPACE` (avoids quota issues in the temporary schema)
#[instrument(skip(conn, password), fields(schema))]
pub fn create_scratch_schema<C: OracleConnection>(
    conn: &C,
    schema: &str,
    password: &str,
) -> Result<(), VerifyError> {
    if !is_scratch_schema(schema) {
        return Err(VerifyError::InvalidScratchSchemaName {
            name: schema.to_string(),
        });
    }

    // The password is interpolated into a quoted DDL literal below; validate it
    // up front so a stray `"` (or other metacharacter) is rejected cleanly
    // instead of corrupting the CREATE USER statement (oracle-clgt.11).
    validate_scratch_password(password)?;

    // CREATE USER
    conn.execute(
        &format!("CREATE USER {schema} IDENTIFIED BY \"{password}\""),
        &[],
    )
    .map_err(|e| VerifyError::SchemaLifecycle {
        message: format!("CREATE USER {schema} failed: {e}"),
    })?;

    // Grant the privileges needed to run common changeset DDL.
    let grants = [
        "CREATE SESSION",
        "CREATE TABLE",
        "CREATE VIEW",
        "CREATE PROCEDURE",
        "CREATE SEQUENCE",
        "CREATE TRIGGER",
        "CREATE TYPE",
        "UNLIMITED TABLESPACE",
    ];
    for priv_name in grants {
        conn.execute(&format!("GRANT {priv_name} TO {schema}"), &[])
            .map_err(|e| VerifyError::SchemaLifecycle {
                message: format!("GRANT {priv_name} TO {schema} failed: {e}"),
            })?;
    }

    Ok(())
}

// ── Core verify function ──────────────────────────────────────────────────────

/// Apply `changeset` to a disposable scratch schema, report per-statement
/// outcomes.
///
/// # Signature
///
/// - `admin_conn`: a connection with DBA/SYSTEM-level privileges (used only to
///   create and drop the scratch user).
/// - `changeset`: the ordered list of DDL statements to apply.
/// - `options`: tuning options; see [`VerifyOptions`].
///
/// # ⚠️  No rollback guarantee
///
/// Oracle DDL auto-commits. Every successful statement permanently modifies
/// the scratch schema state. The scratch schema is dropped in teardown
/// regardless of outcome, so the state is not observable post-run — but within
/// a run, a failure leaves all prior DDL committed. The [`VerifyReport`]
/// records each statement's outcome precisely so the operator sees which
/// statements succeeded before the failure.
///
/// # Errors
///
/// Returns [`VerifyError`] if:
/// - the target schema fails the in-place guard check,
/// - the scratch schema cannot be created or dropped, or
/// - a lower-level [`CicdError`] surfaces.
///
/// Individual statement failures are recorded in the report, not returned as
/// errors — the function returns `Ok(report)` even when some statements fail
/// so the caller receives the full picture.
#[instrument(skip(admin_conn, changeset, options))]
pub fn verify<C: OracleConnection>(
    admin_conn: &C,
    changeset: &VerifyChangeset,
    options: &VerifyOptions,
) -> Result<VerifyReport, VerifyError> {
    if changeset.is_empty() {
        return Err(VerifyError::EmptyChangeset);
    }

    let schema = options.validated_schema()?;
    let password = options.effective_password();

    // Create the scratch schema — guard will drop it on exit.
    create_scratch_schema(admin_conn, &schema, &password)?;
    let mut guard = ScratchSchemaGuard::new(schema.clone(), admin_conn);

    // Connect to the scratch schema to execute changeset DDL.
    // We reuse admin_conn with ALTER SESSION SET CURRENT_SCHEMA so we do not
    // need a second connection object; the guard still uses admin_conn for DROP.
    let switch_sql = format!("ALTER SESSION SET CURRENT_SCHEMA = {schema}");
    admin_conn
        .execute(&switch_sql, &[])
        .map_err(|e| VerifyError::SchemaLifecycle {
            message: format!("ALTER SESSION SET CURRENT_SCHEMA = {schema} failed: {e}"),
        })?;

    let mut rows: Vec<VerifyReportRow> = Vec::new();
    let mut failed = false;

    for stmt in &changeset.statements {
        if failed {
            rows.push(VerifyReportRow {
                ordinal: stmt.ordinal,
                label: stmt.label.clone(),
                outcome: StatementOutcome::Skipped,
            });
            continue;
        }

        let outcome = match admin_conn.execute(&stmt.sql, &[]) {
            Ok(_) => StatementOutcome::Ok,
            Err(e) => {
                failed = true;
                StatementOutcome::Failed {
                    error: e.to_string(),
                }
            }
        };
        rows.push(VerifyReportRow {
            ordinal: stmt.ordinal,
            label: stmt.label.clone(),
            outcome,
        });
    }

    // Restore the session's current schema to the original (SYSTEM) before
    // dropping the scratch user — avoids "cannot drop current schema" ORA errors.
    let _ = admin_conn.execute("ALTER SESSION SET CURRENT_SCHEMA = SYSTEM", &[]);

    // Explicit drop — guard will also fire on exit but this gives us the error.
    guard.drop_now()?;

    Ok(VerifyReport { schema, rows })
}

// ── Unit tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── scratch_schema_name ───────────────────────────────────────────────────

    #[test]
    fn scratch_schema_name_has_verify_t_prefix() {
        let name = scratch_schema_name();
        assert!(
            name.starts_with("VERIFY_T_"),
            "expected VERIFY_T_ prefix, got `{name}`"
        );
    }

    #[test]
    fn scratch_schema_name_for_known_pid() {
        assert_eq!(scratch_schema_name_for_pid(12345), "VERIFY_T_12345");
        assert_eq!(scratch_schema_name_for_pid(0), "VERIFY_T_0");
        assert_eq!(scratch_schema_name_for_pid(u32::MAX), "VERIFY_T_4294967295");
    }

    #[test]
    fn scratch_schema_name_within_oracle_identifier_limit() {
        // Oracle 23ai allows 128-char identifiers; older databases 30.
        // VERIFY_T_ (9) + digits(u32::MAX) (10) = 19 chars — safe.
        let longest = scratch_schema_name_for_pid(u32::MAX);
        assert!(
            longest.len() <= 30,
            "name `{longest}` exceeds 30-char limit ({} chars)",
            longest.len()
        );
    }

    #[test]
    fn is_scratch_schema_accepts_verify_t_prefix_case_insensitively() {
        assert!(is_scratch_schema("VERIFY_T_1234"));
        assert!(is_scratch_schema("verify_t_1234")); // case-insensitive
        assert!(is_scratch_schema("VERIFY_T_"));
    }

    #[test]
    fn is_scratch_schema_rejects_non_prefix_names() {
        assert!(!is_scratch_schema("DEMO"));
        assert!(!is_scratch_schema("SYSTEM"));
        assert!(!is_scratch_schema("VERIFY_1234")); // missing T_
        assert!(!is_scratch_schema("MY_VERIFY_T_1234")); // wrong start
        assert!(!is_scratch_schema(""));
    }

    // ── VerifyOptions ─────────────────────────────────────────────────────────

    #[test]
    fn verify_options_default_allow_in_place_is_false() {
        let opts = VerifyOptions::default();
        assert!(!opts.allow_in_place);
    }

    #[test]
    fn verified_schema_accepts_verify_t_name() {
        let opts = VerifyOptions {
            schema_override: Some(String::from("VERIFY_T_99")),
            ..Default::default()
        };
        let schema = opts.validated_schema().expect("should accept VERIFY_T_99");
        assert_eq!(schema, "VERIFY_T_99");
    }

    #[test]
    fn validated_schema_rejects_non_scratch_by_default() {
        let opts = VerifyOptions {
            allow_in_place: false,
            schema_override: Some(String::from("PRODUCTION")),
            ..Default::default()
        };
        let err = opts.validated_schema().unwrap_err();
        assert!(
            matches!(err, VerifyError::InPlaceVerificationRefused { .. }),
            "expected InPlaceVerificationRefused, got {err:?}"
        );
    }

    #[test]
    fn validated_schema_error_message_cites_flag() {
        let opts = VerifyOptions {
            allow_in_place: false,
            schema_override: Some(String::from("MY_SCHEMA")),
            ..Default::default()
        };
        let msg = opts.validated_schema().unwrap_err().to_string();
        assert!(
            msg.contains("--dangerously-verify-in-place"),
            "error message should cite the flag, got: `{msg}`"
        );
    }

    #[test]
    fn validated_schema_allows_non_scratch_when_flag_set() {
        let opts = VerifyOptions {
            allow_in_place: true,
            schema_override: Some(String::from("STAGING")),
            ..Default::default()
        };
        let schema = opts
            .validated_schema()
            .expect("allow_in_place=true should pass");
        assert_eq!(schema, "STAGING");
    }

    #[test]
    fn effective_schema_uses_process_id_when_no_override() {
        let opts = VerifyOptions::default();
        let schema = opts.effective_schema();
        assert!(schema.starts_with("VERIFY_T_"));
        // Should be parseable as VERIFY_T_<number>
        let suffix = schema.strip_prefix("VERIFY_T_").unwrap();
        let _pid: u32 = suffix.parse().expect("suffix should be a u32 pid");
    }

    // ── StatementOutcome ──────────────────────────────────────────────────────

    #[test]
    fn statement_outcome_display_messages() {
        assert_eq!(StatementOutcome::Ok.to_string(), "OK");
        assert_eq!(StatementOutcome::Skipped.to_string(), "SKIPPED");
        let failed = StatementOutcome::Failed {
            error: String::from("ORA-00942: table or view does not exist"),
        };
        let msg = failed.to_string();
        assert!(msg.starts_with("FAILED:"), "got: {msg}");
        assert!(msg.contains("ORA-00942"), "got: {msg}");
    }

    // ── VerifyReport ──────────────────────────────────────────────────────────

    fn make_report(outcomes: &[StatementOutcome]) -> VerifyReport {
        let rows = outcomes
            .iter()
            .enumerate()
            .map(|(i, o)| VerifyReportRow {
                ordinal: i as u32 + 1,
                label: None,
                outcome: o.clone(),
            })
            .collect();
        VerifyReport {
            schema: String::from("VERIFY_T_1"),
            rows,
        }
    }

    #[test]
    fn verify_report_is_clean_when_all_ok() {
        let report = make_report(&[StatementOutcome::Ok, StatementOutcome::Ok]);
        assert!(report.is_clean());
        assert_eq!(report.ok_count(), 2);
        assert_eq!(report.failed_count(), 0);
        assert_eq!(report.skipped_count(), 0);
    }

    #[test]
    fn verify_report_not_clean_when_any_failure() {
        let report = make_report(&[
            StatementOutcome::Ok,
            StatementOutcome::Failed {
                error: String::from("ORA-00942"),
            },
            StatementOutcome::Skipped,
        ]);
        assert!(!report.is_clean());
        assert_eq!(report.ok_count(), 1);
        assert_eq!(report.failed_count(), 1);
        assert_eq!(report.skipped_count(), 1);
    }

    #[test]
    fn verify_report_failure_messages_collects_errors_in_order() {
        let report = make_report(&[
            StatementOutcome::Failed {
                error: String::from("ORA-00001"),
            },
            StatementOutcome::Ok,
            StatementOutcome::Failed {
                error: String::from("ORA-00942"),
            },
        ]);
        let msgs = report.failure_messages();
        assert_eq!(msgs.len(), 2);
        assert_eq!(msgs[0], (1, String::from("ORA-00001")));
        assert_eq!(msgs[1], (3, String::from("ORA-00942")));
    }

    #[test]
    fn verify_report_is_clean_on_empty_rows() {
        let report = VerifyReport {
            schema: String::from("VERIFY_T_1"),
            rows: vec![],
        };
        assert!(report.is_clean(), "empty rows = vacuously clean");
        assert_eq!(report.ok_count(), 0);
    }

    // ── VerifyChangeset ───────────────────────────────────────────────────────

    #[test]
    fn verify_changeset_new_assigns_ordinals_from_tuples() {
        let cs = VerifyChangeset::new(vec![
            (1, String::from("CREATE TABLE T1 (ID NUMBER)")),
            (2, String::from("CREATE TABLE T2 (ID NUMBER)")),
        ]);
        assert_eq!(cs.statements.len(), 2);
        assert_eq!(cs.statements[0].ordinal, 1);
        assert_eq!(cs.statements[1].ordinal, 2);
        assert!(cs.statements[0].label.is_none());
    }

    #[test]
    fn verify_changeset_with_labels_preserves_labels() {
        let cs = VerifyChangeset::with_labels(vec![(
            1,
            String::from("CREATE TABLE T1 (ID NUMBER)"),
            Some(String::from("CREATE TABLE T1")),
        )]);
        assert_eq!(cs.statements[0].label.as_deref(), Some("CREATE TABLE T1"));
    }

    #[test]
    fn verify_changeset_is_empty_on_default() {
        let cs = VerifyChangeset::default();
        assert!(cs.is_empty());
    }

    #[test]
    fn verify_changeset_is_not_empty_when_populated() {
        let cs = VerifyChangeset::new(vec![(1, String::from("CREATE TABLE T (ID NUMBER)"))]);
        assert!(!cs.is_empty());
    }

    // ── EmptyChangeset error ──────────────────────────────────────────────────

    // A stub OracleConnection for unit tests (no DB required).
    use plsql_catalog::{CatalogError, OracleBackend, OracleBind, OracleConnectionInfo, OracleRow};

    struct StubConn;
    impl OracleConnection for StubConn {
        fn backend(&self) -> OracleBackend {
            OracleBackend::RustOracle
        }
        fn ping(&self) -> Result<(), CatalogError> {
            Ok(())
        }
        fn describe(&self) -> Result<OracleConnectionInfo, CatalogError> {
            Ok(OracleConnectionInfo {
                backend: OracleBackend::RustOracle,
                connect_string: String::from("//localhost/XE"),
                current_schema: Some(String::from("SYSTEM")),
                server_version: String::from("23.0.0.0.0"),
                db_name: String::from("XE"),
                db_domain: String::new(),
                service_name: String::from("XE"),
                instance_name: String::from("xe"),
                server_type: String::from("Dedicated"),
                max_identifier_length: 128,
                max_open_cursors: 500,
            })
        }
        fn query_rows(
            &self,
            _sql: &str,
            _params: &[OracleBind],
        ) -> Result<Vec<OracleRow>, CatalogError> {
            Ok(vec![])
        }
        fn execute(&self, _sql: &str, _params: &[OracleBind]) -> Result<u64, CatalogError> {
            Ok(0)
        }
    }

    #[test]
    fn verify_empty_changeset_returns_error() {
        let conn = StubConn;
        let cs = VerifyChangeset::default();
        let opts = VerifyOptions::default();
        let err = verify(&conn, &cs, &opts).unwrap_err();
        assert!(
            matches!(err, VerifyError::EmptyChangeset),
            "expected EmptyChangeset, got {err:?}"
        );
    }

    #[test]
    fn verify_rejects_non_scratch_schema_before_touching_db() {
        let conn = StubConn;
        let cs = VerifyChangeset::new(vec![(1, String::from("CREATE TABLE T (ID NUMBER)"))]);
        let opts = VerifyOptions {
            allow_in_place: false,
            schema_override: Some(String::from("PRODUCTION")),
            scratch_user_password: None,
        };
        let err = verify(&conn, &cs, &opts).unwrap_err();
        assert!(
            matches!(err, VerifyError::InPlaceVerificationRefused { .. }),
            "expected InPlaceVerificationRefused, got {err:?}"
        );
    }

    #[test]
    fn verify_stub_conn_applies_all_statements_ok() {
        // StubConn.execute always returns Ok(0) — simulates all DDL succeeding.
        let conn = StubConn;
        let cs = VerifyChangeset::new(vec![
            (1, String::from("CREATE TABLE T1 (ID NUMBER)")),
            (2, String::from("CREATE TABLE T2 (ID NUMBER)")),
        ]);
        let opts = VerifyOptions::default(); // VERIFY_T_<pid>
        let report = verify(&conn, &cs, &opts).expect("stub verify should succeed");
        assert!(report.is_clean(), "all stubs should pass");
        assert_eq!(report.ok_count(), 2);
        assert_eq!(report.failed_count(), 0);
        assert_eq!(report.skipped_count(), 0);
    }

    // ── validate_scratch_password (oracle-clgt.11) ────────────────────────────

    #[test]
    fn validate_scratch_password_accepts_default_and_allowlist() {
        // The hard-coded default must pass.
        validate_scratch_password("V3r1fyTmp#2026").expect("default password must validate");
        // Every allowlisted character class.
        validate_scratch_password("Aa0#_$.+-").expect("full allowlist must validate");
    }

    #[test]
    fn validate_scratch_password_rejects_double_quote() {
        // The headline defect: a `"` would close the quoted DDL literal early.
        let err = validate_scratch_password("a\"b").expect_err("double-quote must be rejected");
        assert!(
            matches!(err, VerifyError::InvalidScratchPassword { .. }),
            "expected InvalidScratchPassword, got {err:?}"
        );
    }

    #[test]
    fn validate_scratch_password_rejects_injection_shaped_value() {
        // Even though OCI single-statement execution would reject the trailing
        // statement, we refuse this up front so the operator gets a clear error.
        let err = validate_scratch_password("pw\" ; GRANT DBA TO PUBLIC --")
            .expect_err("injection-shaped password must be rejected");
        assert!(matches!(err, VerifyError::InvalidScratchPassword { .. }));
    }

    #[test]
    fn validate_scratch_password_rejects_empty() {
        let err = validate_scratch_password("").expect_err("empty password must be rejected");
        match err {
            VerifyError::InvalidScratchPassword { reason } => {
                assert!(reason.contains("empty"), "reason should mention empty: {reason}");
            }
            other => panic!("expected InvalidScratchPassword, got {other:?}"),
        }
    }

    #[test]
    fn validate_scratch_password_rejects_over_length() {
        let too_long = "A".repeat(MAX_SCRATCH_PASSWORD_LEN + 1);
        let err =
            validate_scratch_password(&too_long).expect_err("over-length password must be rejected");
        assert!(matches!(err, VerifyError::InvalidScratchPassword { .. }));
        // The boundary itself is accepted.
        validate_scratch_password(&"A".repeat(MAX_SCRATCH_PASSWORD_LEN))
            .expect("max-length password must validate");
    }

    #[test]
    fn validate_scratch_password_rejects_common_metacharacters() {
        for bad in ["a b", "a'b", "a;b", "a/b", "a*b", "a@b", "a%b"] {
            let err = validate_scratch_password(bad)
                .expect_err("metacharacter password must be rejected");
            assert!(
                matches!(err, VerifyError::InvalidScratchPassword { .. }),
                "expected InvalidScratchPassword for `{bad}`, got {err:?}"
            );
        }
    }

    #[test]
    fn create_scratch_schema_rejects_bad_password_before_executing_ddl() {
        // Regression: a corrupting `"` in the password must be rejected before
        // any DDL is sent to the connection (oracle-clgt.11).
        let conn = StubConn;
        let err = create_scratch_schema(&conn, "VERIFY_T_77", "a\"b")
            .expect_err("bad password must be rejected");
        assert!(
            matches!(err, VerifyError::InvalidScratchPassword { .. }),
            "expected InvalidScratchPassword, got {err:?}"
        );
    }

    #[test]
    fn create_scratch_schema_accepts_default_password() {
        // The default password flows through create_scratch_schema cleanly
        // against the always-Ok stub connection.
        let conn = StubConn;
        create_scratch_schema(&conn, "VERIFY_T_88", "V3r1fyTmp#2026")
            .expect("default password must be accepted by create_scratch_schema");
    }

    #[test]
    fn scratch_schema_guard_panics_on_non_verify_t_name() {
        // This test must use catch_unwind because we test a panic path.
        let conn = StubConn;
        let result = std::panic::catch_unwind(|| {
            // This should panic — "PRODUCTION" is not a VERIFY_T_ schema.
            let _guard = ScratchSchemaGuard::new("PRODUCTION", &conn);
        });
        assert!(result.is_err(), "expected panic for non-scratch schema");
    }

    // ── confirm_in_place_verification (PLSQL-CICD-005A / oracle-q2o8) ──────────

    /// Helper: a `read_line` closure yielding a fixed string once.
    fn once(s: &str) -> impl FnMut() -> std::io::Result<String> {
        let mut v = Some(s.to_string());
        move || {
            Ok(v.take()
                .unwrap_or_else(|| panic!("read_line called more than once")))
        }
    }

    #[test]
    fn in_place_not_requested_when_flag_absent_and_no_prompt() {
        let mut out = Vec::new();
        // read_line panics if called — proving the gate short-circuits.
        let decision = confirm_in_place_verification(
            false,
            "HR_PROD",
            || panic!("must not prompt when flag absent"),
            &mut out,
        )
        .expect("flag-absent path is infallible");
        assert_eq!(decision, InPlaceDecision::NotRequested);
        assert!(
            out.is_empty(),
            "no prompt should be written when flag absent"
        );
    }

    #[test]
    fn in_place_confirmed_on_exact_verbatim_match() {
        let mut out = Vec::new();
        let decision = confirm_in_place_verification(true, "HR_PROD", once("HR_PROD\n"), &mut out)
            .expect("exact match must confirm");
        assert_eq!(decision, InPlaceDecision::Confirmed);
        let prompt = String::from_utf8(out).unwrap();
        assert!(prompt.contains("HR_PROD"), "prompt names the schema");
        assert!(prompt.contains("IRREVERSIBLE"), "prompt states the danger");
    }

    #[test]
    fn in_place_confirmed_with_crlf_terminator() {
        let mut out = Vec::new();
        let decision =
            confirm_in_place_verification(true, "HR_PROD", once("HR_PROD\r\n"), &mut out)
                .expect("CRLF-terminated exact match must confirm");
        assert_eq!(decision, InPlaceDecision::Confirmed);
    }

    #[test]
    fn in_place_rejected_on_mismatch() {
        let mut out = Vec::new();
        let err = confirm_in_place_verification(true, "HR_PROD", once("yes\n"), &mut out)
            .expect_err("non-matching input must NOT confirm");
        match err {
            VerifyError::InPlaceConfirmationMismatch { expected, got } => {
                assert_eq!(expected, "HR_PROD");
                assert_eq!(got, "yes");
            }
            other => panic!("expected InPlaceConfirmationMismatch, got {other:?}"),
        }
    }

    #[test]
    fn in_place_rejected_on_case_mismatch_verbatim() {
        // "Verbatim" is case-sensitive — `hr_prod` != `HR_PROD`.
        let mut out = Vec::new();
        let err = confirm_in_place_verification(true, "HR_PROD", once("hr_prod\n"), &mut out)
            .expect_err("case-different input must NOT confirm");
        assert!(matches!(
            err,
            VerifyError::InPlaceConfirmationMismatch { .. }
        ));
    }

    #[test]
    fn in_place_rejected_on_empty_input() {
        let mut out = Vec::new();
        let err = confirm_in_place_verification(true, "HR_PROD", once("\n"), &mut out)
            .expect_err("empty input must NOT confirm");
        assert!(matches!(
            err,
            VerifyError::InPlaceConfirmationMismatch { got, .. } if got.is_empty()
        ));
    }

    #[test]
    fn in_place_mismatch_keeps_verify_options_safe() {
        // End-to-end seam check: a failed confirmation means the caller never
        // sets allow_in_place, so VerifyOptions still refuses an in-place run.
        let mut out = Vec::new();
        let confirmed = confirm_in_place_verification(true, "HR_PROD", once("nope\n"), &mut out)
            .map(|d| d == InPlaceDecision::Confirmed)
            .unwrap_or(false);
        let opts = VerifyOptions {
            allow_in_place: confirmed,
            schema_override: Some("HR_PROD".to_string()),
            ..VerifyOptions::default()
        };
        assert!(
            matches!(
                opts.validated_schema(),
                Err(VerifyError::InPlaceVerificationRefused { .. })
            ),
            "unconfirmed in-place must stay refused by VerifyOptions"
        );
    }
}
